Repository teamleadercrm/ui, pull requests merged in 2018-07, with the labels that each got.

#301 Fix global bullet styles
  components/bullet/theme.css
Labels: bug, ready

#298 Render Toasts in a container and update animation
  components/index.js
  components/toast/Toast.js
  components/toast/ToastContainer.js
  components/toast/index.js
  components/toast/theme.css
  stories/toast.js
Labels: enhancement, new component, ready

#305 Re-calculate Popover position on screen resize
  components/popover/Popover.js
Labels: ready

#307 Enhancement/pause toast timeout on hover
  components/toast/Toast.js
Labels: enhancement, ready

#308 Add the toastContainer with its new animations to master
  components/index.js
  components/toast/Toast.js
  components/toast/ToastContainer.js
  components/toast/index.js
  components/toast/theme.css
  stories/toast.js
Labels: ready

#310 Add option to control the checkbox size in the Datagrid
  components/checkbox/Checkbox.js
  components/datagrid/BodyRow.js
  components/datagrid/DataGrid.js
  components/datagrid/HeaderRow.js
  stories/datagrid.js
Labels: enhancement, ready

#313 Update disabled button styles
  components/button/theme.css
Labels: enhancement, ready, storybook

#311 Change checkbox background color to white
  components/checkbox/theme.css
Labels: ready, storybook

#309 Indicate that a user has selected some datagrid items
  components/checkbox/Checkbox.js
  components/checkbox/theme.css
  components/datagrid/DataGrid.js
  components/datagrid/HeaderRow.js
  stories/checkbox.js
Labels: enhancement, ready

#318 Send an empty array to the onSelectionChange handler when the comparable ID changes
  components/datagrid/DataGrid.js
Labels: ready

#320 Change the Datagrid and checkbox's default checkbox size
  components/checkbox/Checkbox.js
  components/datagrid/DataGrid.js
  stories/datagrid.js
Labels: ready

#322 Fix the animation when removing a toast
  CHANGELOG.md
  components/toast/ToastContainer.js
  stories/toast.js
Labels: bug

#321 Don't vertically center or resize the icon for when error is multiline
  components/input/Input.js
  components/input/theme.css
Labels: bug, ready

#323 Release 0.11.1
  CHANGELOG.md
  package.json
Labels: release

#324 🐛 Make sure IconMenu can receive Box props
  CHANGELOG.md
  components/menu/IconMenu.js
Labels: enhancement, ready
