Repository teamleadercrm/ui, pull requests merged in 2018-09, with the labels that each got.

#345 Add an Async select component
  CHANGELOG.md
  components/index.js
  components/select/AsyncSelect.js
  components/select/index.js
  stories/select.js
Labels: new component, ready

#346 Input: remove precision prop
  CHANGELOG.md
  components/input/Input.js
  stories/input.js
Labels: bug, ready

#348 Bugfix: extra icon margin on tooltipped buttons
  CHANGELOG.md
  components/button/Button.js
  components/button/LinkButton.js
  components/button/theme.css
Labels: bug, ready

#350 Release 0.13.0
  CHANGELOG.md
  package.json
Labels: ready, release

#349 Input: decouple from redux forms
  CHANGELOG.md
  components/input/FieldInputPropTypes.js
  components/input/Input.js
  stories/input.js
Labels: enhancement, ready

#347 DatePicker: add a Box wrapper with boxProps
  CHANGELOG.md
  components/datepicker/DatePicker.js
  components/datepicker/DatePickerInput.js
  components/datepicker/DatePickerInputRange.js
  components/datepicker/DatePickerRange.js
Labels: enhancement, ready

#353 DatePicker: decouple from redux forms
  CHANGELOG.md
  components/datepicker/DatePickerInput.js
  components/datepicker/DatePickerInputRange.js
  components/input/InputMetaPropTypes.js
  stories/datePicker.js
Labels: enhancement, ready

#354 Select: add a Box wrapper with boxProps
  CHANGELOG.md
  components/select/Select.js
Labels: enhancement, ready

#355 Datagrid: first and last cell extra padding
  components/datagrid/theme.css
Labels: enhancement, ready

#357 IslandGroup: apply box props to the Box wrapper
  CHANGELOG.md
  components/island/IslandGroup.js
Labels: enhancement, ready

#358 IslandGroup: vertical segmentation
  CHANGELOG.md
  components/island/IslandGroup.js
  components/island/theme.css
  stories/island.js
Labels: enhancement, ready

#360 Release 0.14.0
  CHANGELOG.md
  package.json
Labels: ready, release

#359 Select: error & help text
  CHANGELOG.md
  components/select/Select.js
  components/select/constants.js
  components/select/theme.css
Labels: enhancement, ready

#362 Blur is not always available
  CHANGELOG.md
  components/button/Button.js
  components/button/IconButton.js
  components/button/LinkButton.js
Labels: bug

#361 IslandGroup: refactor to solve multiple small bugs
  CHANGELOG.md
  components/island/IslandGroup.js
  components/island/theme.css
  stories/island.js
Labels: bug, enhancement, ready

#364 Storybook: remove accessibility addon
  .storybook/addons.js
  package.json
  stories/avatars.js
  stories/badge.js
  stories/banners.js
  stories/box.js
  stories/bullet.js
  stories/button.js
  stories/buttonGroup.js
  stories/checkbox.js
  stories/counter.js
  stories/datagrid.js
  stories/datePicker.js
  stories/dialogs.js
  stories/iconButton.js
  stories/icons.js
  stories/input.js
  stories/island.js
  stories/linkButton.js
  stories/loadingMolecule.js
  stories/loadingSpinner.js
  stories/menu.js
  stories/message.js
  stories/pagination.js
  stories/popover.js
  stories/progressTracker.js
  stories/qTip.js
  stories/radio.js
  stories/section.js
  stories/select.js
  stories/statusBullet.js
  stories/statusLabel.js
  stories/tab.js
  stories/tag.js
  stories/toast.js
  stories/toggle.js
  stories/tooltip.js
  stories/typography.js
Labels: ready, storybook

#343 Refactor Popover
  CHANGELOG.md
  components/popover/Popover.js
  components/popover/positionCalculation.js
  components/popover/theme.css
  stories/popover.js
Labels: WIP, enhancement

#365 Input: bugfix when adjusting the value in a number type input field
  components/input/Input.js
  stories/input.js
Labels: bug, ready

#367 Input: output value as a string & fire onBlur event when blurring input field
  components/input/Input.js
Labels: enhancement, ready

#368 Release 0.15.0
  CHANGELOG.md
  package.json
Labels: ready, release

#371 Storybook: addon backgrounds
  .storybook/addons.js
  .storybook/config.js
  package.json
Labels: ready, storybook

#372 Storybook: move Avatar data to the static folder
  static/data/avatar.js
  stories/avatars.js
Labels: enhancement, ready, storybook

#373 Release 0.15.1
  CHANGELOG.md
  package.json
Labels: ready, release

#374 Upgrade to webpack 4
  CHANGELOG.md
  package.json
Labels: bug, package update, ready

#375 Release 0.15.2
  CHANGELOG.md
  package.json
Labels: ready, release

#376 Merge LinkButton into Button
  CHANGELOG.md
  components/button/Button.js
  components/button/index.js
  components/button/theme.css
  components/index.js
  components/toast/Toast.js
  stories/button.js
  stories/pagination.js
Labels: enhancement, ready

#378 Loading spinner colours update
  CHANGELOG.md
  components/button/Button.js
  components/loadingSpinner/LoadingSpinner.js
  components/loadingSpinner/theme.css
  components/toast/Toast.js
  stories/loadingSpinner.js
Labels: enhancement, ready

#377 Popover refactor: remove factory pattern
  CHANGELOG.md
  components/index.js
  components/popover/Popover.js
  components/popover/index.js
  components/popover/positionCalculation.js
  stories/popover.js
Labels: enhancement, ready

#380 Button level link add LoadingSpinner
  CHANGELOG.md
  components/button/Button.js
  components/button/theme.css
Labels: enhancement, ready
