Repository teamleadercrm/ui, pull requests merged in 2018-08, with the labels that each got.

#326 [#314] Fix button styling for Safari
  CHANGELOG.md
  components/button/theme.css
Labels: ready

#327 Update start script
  README.md
  package.json
Labels: ready

#325 ♻️ Center-align cells when DataGrid is selectable
  CHANGELOG.md
  components/datagrid/BodyRow.js
  components/datagrid/HeaderRow.js
Labels: enhancement, ready

#280 Select component
  CHANGELOG.md
  components/index.js
  components/select/Select.js
  components/select/constants.js
  components/select/index.js
  components/select/theme.css
  package.json
  static/data/select.js
  stories/select.js
Labels: new component, ready

#328 Label: extra check for Select component so 'optional' wouldn't render twice
  CHANGELOG.md
  components/label/Label.js
Labels: bug, ready

#329 Release 0.11.2 preparations
  CHANGELOG.md
  package.json
Labels: ready, release

#331 Remove deprecated lifecycles
  CHANGELOG.md
  components/datagrid/DataGrid.js
  components/overlay/Overlay.js
Labels: enhancement, ready

#330 Refactor menu component
  components/menu/Menu.js
Labels: enhancement, ready

#334 Prevent double borders on input fields with connected buttons
  CHANGELOG.md
  components/input/theme.css
Labels: enhancement, ready

#333 Add changes to Menu to the CHANGELOG
  CHANGELOG.md
Labels: ready

#335 [TU-91] Ability to not render spinner controls on Input fields
  CHANGELOG.md
  components/input/Input.js
  components/input/theme.css
  stories/input.js
Labels: enhancement, ready

#336 [TU-88] Button: custom element override
  CHANGELOG.md
  components/button/Button.js
  components/button/IconButton.js
  components/button/LinkButton.js
  stories/button.js
  stories/iconButton.js
  stories/linkButton.js
Labels: enhancement, ready

#337 Release 0.12.0 preparations
  CHANGELOG.md
  package.json
Labels: ready, release

#338 Button: only render disabled attribute when element is button
  CHANGELOG.md
  components/button/Button.js
  components/button/IconButton.js
  components/button/LinkButton.js
  components/button/theme.css
Labels: enhancement, ready

#339 Pass the event from the Checkbox to the DataGrid onSelectionChange handler
  CHANGELOG.md
  components/datagrid/DataGrid.js
Labels: enhancement, ready

#340 Release 0.12.1
  CHANGELOG.md
  package.json
Labels: release

#341 [TU-105] LinkButton display as square
  CHANGELOG.md
  components/button/Button.js
  components/button/theme.css
  stories/linkButton.js
Labels: ready

#344 Update Input
  components/input/Input.js
Labels: enhancement, ready
