Repository teamleadercrm/ui, pull requests merged in 2018-05, with the labels that each got.

#245 🐛 Popover SVG anchor element
  components/popover/positionCalculation.js
  stories/popover.js
Labels: bug, enhancement, ready

#246 :bug: check if onChange is explicitly set for non-redux-forms
  components/input/Input.js
Labels: bug, enhancement, ready

#248 Popover colors
  components/popover/Popover.js
  components/popover/theme.css
  stories/popover.js
Labels: enhancement, ready

#249 Check if nextProps.value is not undefined before updating state
  components/input/Input.js
Labels: bug, ready

#250 Export boxProps and add pickBoxProps method
  components/box/boxProps.js
  components/box/index.js
  components/box/omitBoxProps.js
  package.json
Labels: enhancement, ready

#252 Label: make it possible to add box props to the label Box container
  components/label/Label.js
Labels: enhancement, ready

#254 When propType.name is 'instanceOf' return propType.value
  stories/components/propTable/PropTable.js
Labels: enhancement, storybook

#255 Update '@sambego/storybook-state' to the latest version
  package.json
Labels: package update, ready, storybook

#253 Lockscroll props passing
  components/popover/Popover.js
Labels: enhancement, ready
