Repository teamleadercrm/ui, pull requests merged in 2018-02, with the labels that each got.

#196 📦 Upgrade to React 16.2
  package.json
Labels: package update

#97 Component/input
  .storybook/config.js
  components/index.js
  components/input/Input.js
  components/input/InputMetaPropTypes.js
  components/input/index.js
  components/input/theme.css
  components/label/Label.js
  components/label/index.js
  components/label/theme.css
  stories/input.js
Labels: new component, ready

#198 Update npm packages to latest versions
  package.json
Labels: package update, ready

#203 Storybook: update stories and integrate with Knobs
  stories/bullet.js
Labels: enhancement, ready, storybook

#202 Counter: add the children prop so we can show a Tooltip
  components/counter/Counter.js
  stories/counter.js
Labels: enhancement, ready

#201 Tag: add the children prop so we can show a Tooltip
  components/tag/Tag.js
  stories/tag.js
Labels: enhancement, ready

#204 Avatar: component & story updates
  components/avatar/Avatar.js
  components/avatar/theme.css
  stories/avatars.js
Labels: enhancement, ready

#200 Icon component
  components/icon/Icon.js
  components/icon/index.js
  components/icon/theme.css
  components/index.js
  stories/icons.js
Labels: new component, ready

#205 Button story: replace the broken icon with one that actually works
  stories/button.js
Labels: bug, ready, storybook

#208 Make the StatusBullet explicitly a content-box.
  components/statusBullet/theme.css
Labels: bug, ready
