Repository teamleadercrm/ui, pull requests merged in 2018-04, with the labels that each got.

#214 PropType descriptions
  components/avatar/Avatar.js
  components/badge/Badge.js
  components/banner/Banner.js
  components/bullet/Bullet.js
  components/button/Button.js
  components/button/ButtonGroup.js
  components/checkbox/Checkbox.js
  components/dialog/Dialog.js
Labels: WIP, enhancement, storybook

#215 Storybook: hide all unneeded PropTables
  stories/avatars.js
Labels: WIP, enhancement, storybook

#239 Upgrade to React 16.3
  package.json
Labels: package update

#241 Render the Tooltip in the correct document
  components/hoc/DocumentObjectProvider/DocumentObjectProvider.js
  components/hoc/DocumentObjectProvider/index.js
  components/tooltip/Tooltip.js
  components/tooltip/index.js
Labels: bug, enhancement

#240 🔥 Remove inheriting of color for button on hover
  components/button/theme.css
Labels: bug, enhancement, ready

#236 Allow patch updates for our own dependency packages
  package.json
Labels: enhancement, package update, ready

#242 Fix input triggering onChange for its old value when receiving props
  components/input/Input.js
Labels: bug, ready

#243 Active button in button group
  components/box/index.js
  components/box/omitBoxProps.js
  components/button/Button.js
  components/button/ButtonGroup.js
  components/button/theme.css
  stories/buttonGroup.js
Labels: enhancement, ready

#244 Input should not have a max width
  components/input/theme.css
Labels: enhancement, ready
