Repository teamleadercrm/ui, pull requests merged in 2018-11, with the labels that each got.

#430 [TU-194] NumericInput: Fix change via spinner
  CHANGELOG.md
  components/input/NumericInput.js
Labels: bug, ready

#426 InputBase: Extract SingleLineInputBase
  components/input/Input.js
  components/input/InputBase.js
  components/input/NumericInput.js
  components/input/SingleLineInputBase.js
  components/input/index.js
  components/input/theme.css
  stories/input.js
Labels: enhancement, new component, ready

#427 Feature: TextArea
  components/index.js
  components/input/TextArea.js
  components/input/index.js
  components/input/theme.css
  stories/input.js
Labels: new component, ready

#431 [TU-196] NumericInput: Spinner buttons submit forms
  CHANGELOG.md
  components/input/NumericInput.js
Labels: enhancement, ready

#423 DataGrid maintenance
  components/datagrid/BodyRow.js
  components/datagrid/Cell.js
  components/datagrid/DataGrid.js
  components/datagrid/HeaderCell.js
  components/datagrid/HeaderRow.js
  stories/datagrid.js
Labels: maintenance, ready

#433 TextArea: rename to Textarea
  CHANGELOG.md
  components/index.js
  components/input/Textarea.js
  components/input/index.js
  components/input/theme.css
  stories/input.js
Labels: maintenance, ready

#434 Release 0.18.0
  CHANGELOG.md
  package.json
Labels: ready, release

#436 [TU-152] Button (link): background color update
  CHANGELOG.md
  components/button/theme.css
Labels: enhancement, ready

#438 Toast: text color fix
  CHANGELOG.md
  components/toast/Toast.js
Labels: bug, ready

#439 [TU-59] Toast: prevent the spinner from being squeezed
  CHANGELOG.md
  components/toast/theme.css
Labels: bug, ready

#416 Proposal: HOC InjectTheme
  components/hoc/withTheme/index.js
  components/hoc/withTheme/withTheme.js
Labels: enhancement, new component, ready

#442 withTheme: Document change
  CHANGELOG.md
Labels: ready

#444 [TU-205] withTheme: maintenance
  src/components/hoc/withTheme/index.js
  src/components/hoc/withTheme/withTheme.js
Labels: maintenance, ready

#447 [TU-161] NumericInput: disable spinner controls on min/max
  CHANGELOG.md
  src/components/input/NumericInput.js
  src/components/input/theme.css
Labels: enhancement, ready

#445 Storybook/input stories
  stories/checkbox.js
  stories/datePicker.js
  stories/input.js
  stories/label.js
  stories/radio.js
  stories/select.js
  stories/toggle.js
Labels: enhancement, ready, storybook

#448 [TU-208] Add size constants
  CHANGELOG.md
  src/constants/index.js
  src/constants/sizes.js
  src/index.js
Labels: enhancement, ready

#446 [TU-101] Badge: prevent text wrapping
  CHANGELOG.md
  src/components/badge/theme.css
Labels: enhancement, ready

#453 Add displayName to all the Typography components
  CHANGELOG.md
  src/components/typography/index.js
Labels: enhancement, ready, storybook

#452 Maintenance: uglify our js code
  CHANGELOG.md
  gulpfile.js
  package.json
Labels: enhancement, maintenance, ready

#451 [TU-193] Avatar multiple shapes
  CHANGELOG.md
  src/components/avatar/Avatar.js
  src/components/avatar/theme.css
  stories/avatars.js
Labels: enhancement, ready

#443 [TU-204] Dialog: create DialogBase and update Dialog
  CHANGELOG.md
  src/components/dialog/Dialog.js
  src/components/dialog/DialogBase.js
  src/components/dialog/index.js
  src/index.js
  stories/dialogs.js
Labels: enhancement, new component, ready

#455 Release: 0.19.0
  CHANGELOG.md
  package.json
Labels: ready, release

#454 [TU-209] Select: use our new COLOR object
  src/components/select/Select.js
  src/components/select/constants.js
Labels: maintenance, ready

#458 Update the readme: how to make a release
  README.md
Labels: enhancement, maintenance, ready

#456 [TU-204] Dialog: make body scrollable
  CHANGELOG.md
  src/components/dialog/Dialog.js
  src/components/dialog/DialogBase.js
  src/components/dialog/theme.css
Labels: enhancement, ready

#460 Radio button: replace splitProps with pickBoxProps & omitBoxProps
  CHANGELOG.md
  src/components/radio/RadioButton.js
Labels: maintenance, ready

#459 Storybook: add a playground story to play around
  stories/playground.js
Labels: ready, storybook

#462 DataGrid: add displayName to all subcomponents
  CHANGELOG.md
  src/components/datagrid/DataGrid.js
  src/components/progressTracker/ProgressTracker.js
Labels: enhancement, maintenance, ready

#464 Typography: set 'darkest' as default tint
  CHANGELOG.md
  src/components/checkbox/Checkbox.js
  src/components/radio/RadioButton.js
  src/components/toggle/Toggle.js
  src/components/typography/Text.js
  stories/input.js
  stories/playground.js
Labels: enhancement, ready

#463 Checkbox & Toggle: replace splitProps with pickBoxProps & omitBoxProps
  CHANGELOG.md
  src/components/checkbox/Checkbox.js
  src/components/toggle/Toggle.js
Labels: maintenance, ready

#465 DatePicker: don't change date when a disabled date was selected
  CHANGELOG.md
  src/components/datepicker/DatePickerInput.js
Labels: bug, ready

#461 [TU-153] Dialog: separate footer and body
  CHANGELOG.md
  src/components/dialog/Dialog.js
  src/components/dialog/theme.css
Labels: enhancement, ready

#466 Release/0.19.1
  CHANGELOG.md
  package.json
Labels: ready, release

#469 [TU-155] Datagrid: prevent grey border from overlaying the loading bar
  CHANGELOG.md
  src/components/datagrid/DataGrid.js
  src/components/datagrid/theme.css
Labels: enhancement, ready

#467 [TU-224] Popover: work around default stretching
  CHANGELOG.md
  src/components/popover/Popover.js
  src/components/popover/positionCalculation.js
  stories/popover.js
Labels: enhancement, ready

#470 DataGrid: replace the custom resize events
  CHANGELOG.md
  src/components/datagrid/DataGrid.js
Labels: maintenance, ready

#472 [TU-215] DataGrid: border & rounded corners
  CHANGELOG.md
  src/components/datagrid/DataGrid.js
  src/components/datagrid/HeaderRowOverlay/theme.css
  src/components/datagrid/theme.css
  stories/datagrid.js
Labels: enhancement, ready

#474 [TU-114] Passport & EmptyPassport components
  CHANGELOG.md
  src/components/passport/EmptyPassport.js
  src/components/passport/Passport.js
  src/components/passport/index.js
  src/components/passport/theme.css
  src/index.js
  stories/passport.js
Labels: new component, ready

#475 Release 0.19.2
  CHANGELOG.md
  package.json
Labels: ready, release

#476 [TU-238] Select: add possibility to create a new option
  CHANGELOG.md
  src/components/select/Select.js
  stories/select.js
Labels: enhancement, ready

#477 Feature: ScrollContainer
  CHANGELOG.md
  src/components/scrollContainer/ScrollContainer.js
  src/components/scrollContainer/index.js
  src/components/scrollContainer/theme.css
  src/index.js
  stories/scrollContainer.js
Labels: new component, ready
