Repository teamleadercrm/ui, pull requests merged in 2018-10, with the labels that each got.

#381 Link: extend with an icon & iconPlacement
  CHANGELOG.md
  components/link/Link.js
  components/link/theme.css
  stories/link.js
Labels: enhancement, ready

#384 Input: refactor spinner positioning
  components/input/theme.css
Labels: enhancement, ready

#388 Link: Add string as a possible prop type
  CHANGELOG.md
  components/link/Link.js
Labels: enhancement, ready

#383 [TU-67] Input: prefix & suffix
  CHANGELOG.md
  components/input/Input.js
  components/input/theme.css
  stories/input.js
Labels: enhancement, ready

#385 [TU-132] LoadingBar component
  CHANGELOG.md
  components/index.js
  components/loadingBar/LoadingBar.js
  components/loadingBar/index.js
  components/loadingBar/theme.css
  stories/loadingBar.js
Labels: new component, ready

#387 [TU 138] Box alignItems missing values
  CHANGELOG.md
  components/box/Box.js
  components/box/theme.css
Labels: enhancement, ready

#389 Release 0.16.0
  CHANGELOG.md
  package.json
Labels: ready, release

#391 [TU-132] DataGrid add loading state
  CHANGELOG.md
  components/datagrid/DataGrid.js
  components/datagrid/theme.css
  stories/datagrid.js
Labels: enhancement, ready

#393 Input: replace spinner buttons
  components/input/Input.js
  components/input/theme.css
Labels: enhancement, ready

#395 [Proposal] Fix labels
  CHANGELOG.md
  components/label/Label.js
Labels: help wanted, question

#398 Select: fix Storybook knobs
  stories/select.js
Labels: enhancement, ready, storybook

#397 Select: remove the max-width so it becomes fluid
  CHANGELOG.md
  components/select/theme.css
Labels: enhancement, ready

#399 Dialog: add flex behavior to the inner wrapper
  CHANGELOG.md
  components/dialog/theme.css
Labels: bug, ready

#400 Select: replace the built-in clear indicator button
  CHANGELOG.md
  components/select/Select.js
Labels: enhancement, ready

#403 DataGrid.HeaderRowOverlay: Fix prop type
  CHANGELOG.md
  components/datagrid/HeaderRowOverlay/HeaderRowOverlay.js
Labels: ready

#401 Input: spinner button opacity & position adjustments
  CHANGELOG.md
  components/input/Input.js
  components/input/theme.css
Labels: enhancement, ready

#402 Select: dropdown arrow opacity & position adjustments
  CHANGELOG.md
  components/select/Select.js
  components/select/theme.css
Labels: enhancement, ready

#405 Release 0.16.1
  CHANGELOG.md
  package.json
Labels: ready, release

#406 Input: extract HelpText
  CHANGELOG.md
  components/datepicker/DatePickerInput.js
  components/datepicker/DatePickerInputRange.js
  components/helptext/HelpText.js
  components/helptext/index.js
  components/index.js
  components/input/Input.js
  components/select/Select.js
Labels: new component, ready

#407 Input: extract ErrorText
  CHANGELOG.md
  components/datepicker/DatePickerInput.js
  components/datepicker/DatePickerInputRange.js
  components/errorText/ErrorText.js
  components/errorText/index.js
  components/errorText/theme.css
  components/index.js
  components/input/Input.js
  components/select/Select.js
Labels: new component, ready

#408 Input & Select: equal heights
  CHANGELOG.md
  components/input/theme.css
  components/select/Select.js
Labels: enhancement, ready

#409 Move static folder inside stories
  stories/avatars.js
  stories/datagrid.js
  stories/select.js
  stories/static/avatars/1.png
  stories/static/avatars/2.png
  stories/static/avatars/3.png
  stories/static/avatars/4.png
  stories/static/avatars/5.png
  stories/static/avatars/6.png
  stories/static/avatars/7.png
  stories/static/avatars/8.png
  stories/static/data/avatar.js
  stories/static/data/datagrid.js
  stories/static/data/select.js
  stories/static/data/tab.js
  stories/tab.js
Labels: ready, storybook

#410 DatePicker: fix collapsing when container is resizing
  CHANGELOG.md
  components/datepicker/theme.css
Labels: bug, ready

#412 Fix DataGrid: Error when not supplying HeaderRowOverlay
  CHANGELOG.md
  components/datagrid/DataGrid.js
Labels: bug, ready

#413 Import components from their own folders
  components/datepicker/DatePickerInput.js
  components/datepicker/DatePickerInputRange.js
  components/errorText/ErrorText.js
  components/helptext/HelpText.js
  components/input/Input.js
  components/select/Select.js
  stories/components/propTable/PropTable.js
Labels: bug, ready

#415 [TU-111] DatePickerInput: Consistent text alignment
  CHANGELOG.md
  components/datepicker/theme.css
Labels: enhancement, ready

#417 [TU-160] Input: Set cursor to pointer on spinners
  CHANGELOG.md
  components/input/theme.css
Labels: enhancement, ready

#414 DatePickerInput: remove onDayClick handler and let DayPicker handle it
  CHANGELOG.md
  components/datepicker/DatePickerInput.js
Labels: enhancement, ready

#419 NumericInput: Fix spinner color for inverse input
  components/input/NumericInput.js
Labels: enhancement, ready

#418 Input: Extract ValidationText
  CHANGELOG.md
  components/datepicker/DatePickerInput.js
  components/datepicker/DatePickerInputRange.js
  components/errorText/index.js
  components/helptext/index.js
  components/index.js
  components/input/InputBase.js
  components/select/Select.js
  components/validationText/ErrorText.js
  components/validationText/HelpText.js
  components/validationText/ValidationText.js
  components/validationText/index.js
  components/validationText/theme.css
Labels: enhancement, new component, ready

#420 [TU-118] Component z-indexes
  CHANGELOG.md
  components/datepicker/theme.css
  components/dialog/theme.css
  components/menu/theme.css
  components/popover/theme.css
  components/qTip/theme.css
  components/select/Select.js
  components/toast/theme.css
Labels: enhancement, ready

#421 Release 0.17.0
  CHANGELOG.md
  package.json
Labels: ready, release

#422 AvatarStack maintenance
  components/avatar/AvatarStack.js
Labels: enhancement, ready

#424 Primary & Secondary Button: fix border style when disabled
  CHANGELOG.md
  components/button/theme.css
Labels: enhancement, ready

#425 Constants for colors & tints
  components/badge/Badge.js
  constants/colors.js
  constants/index.js
  package.json
  stories/badge.js
Labels: maintenance, ready

#428 Input: fix focus state when you have custom onFocus/onBlur event handlers
  CHANGELOG.md
  components/input/InputBase.js
Labels: bug, ready
