Repository teamleadercrm/ui, pull requests merged in 2018-06, with the labels that each got.

#257 DatePickerRange component
  components/datepicker/DatePickerRange.js
  components/datepicker/index.js
  components/datepicker/utils.js
  components/index.js
  stories/datePicker.js
Labels: new component, ready

#258 DatePickerInput component
  components/datepicker/DatePickerInput.js
  components/datepicker/index.js
  components/index.js
  stories/datePicker.js
Labels: new component, ready

#259 DatePickerInputRange component
  components/datepicker/DatePickerInputRange.js
  components/datepicker/index.js
  components/index.js
  stories/datePicker.js
Labels: new component, ready

#220 Remove named export in component files
  components/button/Button.js
  components/button/IconButton.js
  components/button/LinkButton.js
  components/checkbox/Checkbox.js
  components/dialog/Dialog.js
  components/menu/MenuDivider.js
  components/menu/index.js
  components/overlay/Overlay.js
  components/overlay/index.js
  components/radio/RadioButton.js
  components/radio/RadioGroup.js
  components/radio/index.js
  components/toggle/Toggle.js
Labels: enhancement, ready

#261 Lint storybook stories
  .eslintrc
  .prettierrc
  package.json
  stories/avatars.js
  stories/badge.js
  stories/banners.js
  stories/bullet.js
  stories/button.js
  stories/buttonGroup.js
  stories/checkbox.js
  stories/components/propTable/PropTable.js
  stories/counter.js
  stories/datagrid.js
  stories/datePicker.js
  stories/dialogs.js
  stories/iconButton.js
  stories/icons.js
  stories/input.js
  stories/island.js
  stories/link.js
  stories/linkButton.js
  stories/loadingMolecule.js
  stories/loadingSpinner.js
  stories/menu.js
  stories/message.js
  stories/pagination.js
  stories/popover.js
  stories/qTip.js
  stories/radio.js
  stories/section.js
  stories/statusBullet.js
  stories/statusLabel.js
  stories/tab.js
  stories/tag.js
  stories/toast.js
  stories/toggle.js
  stories/tooltip.js
  stories/typography.js
Labels: enhancement, ready, storybook

#263 Also check for any value passed by redux-form in getDerivedStateFromProps
  components/input/Input.js
Labels: bug, ready

#267 Add story for our Box component
  stories/box.js
Labels: ready, storybook

#270 Avatar: move static propTypes & defaultProps outside of the component class
  components/avatar/Avatar.js
Labels: enhancement, ready

#269 Box: move static propTypes & defaultProps outside of the component class
  components/box/Box.js
Labels: enhancement, ready

#272 Update: move propTypes & defaultProps outside class
  .babelrc
  components/badge/Badge.js
  components/banner/Banner.js
  components/bullet/Bullet.js
  components/button/Button.js
  components/button/ButtonGroup.js
  components/button/IconButton.js
  components/button/LinkButton.js
  components/checkbox/Checkbox.js
  components/compactMessage/CompactMessage.js
  components/counter/Counter.js
  components/datagrid/BodyRow.js
  components/datagrid/Cell.js
  components/datagrid/DataGrid.js
  components/datagrid/FooterRow.js
  components/datagrid/HeaderCell.js
  components/datagrid/HeaderRow.js
  components/datagrid/Row.js
  components/dialog/Dialog.js
  components/icon/Icon.js
  components/input/Input.js
  components/island/Island.js
  components/label/Label.js
  components/link/Link.js
  components/loadingMolecule/LoadingMolecule.js
  components/loadingSpinner/LoadingSpinner.js
  components/menu/IconMenu.js
  components/menu/Menu.js
  components/menu/MenuItem.js
  components/message/Message.js
  components/overlay/Overlay.js
  components/pagination/Pagination.js
  components/qTip/QTip.js
  components/radio/RadioButton.js
  components/radio/RadioGroup.js
  components/section/Section.js
  components/statusBullet/StatusBullet.js
  components/statusLabel/StatusLabel.js
  components/tab/IconTab.js
  components/tab/TabGroup.js
  components/tab/TitleTab.js
  components/tag/Tag.js
  components/toast/Toast.js
  components/toggle/Toggle.js
  components/tooltip/Tooltip.js
  components/typography/Monospaced.js
  components/typography/Text.js
  package.json
Labels: enhancement, ready

#268 replace for attribute with htmlFor
  stories/input.js
Labels: ready, storybook

#273 Apply correct border radius on a single button in a ButtonGroup
  components/button/theme.css
Labels: bug, ready

#274 Lint all the CSS files
  components/badge/theme.css
  components/box/theme.css
  components/button/theme.css
  components/checkbox/theme.css
  components/datepicker/theme.css
  components/dialog/theme.css
  components/input/theme.css
  components/loadingMolecule/theme.css
  components/loadingSpinner/theme.css
  components/menu/theme.css
  components/overlay/theme.css
  components/pagination/theme.css
  components/popover/theme.css
  components/radio/theme.css
  components/section/theme.css
  components/tab/theme.css
  components/tag/theme.css
  components/toast/theme.css
  components/toggle/theme.css
  components/tooltip/theme.css
  package.json
Labels: ready

#275 update H1 font weight description
  stories/typography.js
Labels: enhancement, ready

#276 Eliminate constructors
  components/banner/Banner.js
  components/checkbox/Checkbox.js
  components/datagrid/DataGrid.js
  components/dialog/Dialog.js
  components/loadingMolecule/LoadingMolecule.js
  components/overlay/Overlay.js
  components/popover/Popover.js
  components/radio/RadioButton.js
  components/radio/RadioGroup.js
  components/tab/IconTab.js
  components/tab/TitleTab.js
  components/toast/Toast.js
  components/toggle/Toggle.js
  components/tooltip/Tooltip.js
Labels: enhancement, ready

#278 Enhance Badge component styles
  components/badge/Badge.js
  components/badge/theme.css
  stories/badge.js
Labels: enhancement, ready

#279 Remove redundant component proptypes
  stories/banners.js
  stories/buttonGroup.js
  stories/popover.js
  stories/qTip.js
Labels: enhancement, ready

#281 Update Tag component styles
  components/tag/Tag.js
  components/tag/theme.css
  stories/tag.js
Labels: enhancement, ready

#282 Fix/fix lint errors
  stories/components/propTable/PropTable.js
  stories/datagrid.js
  stories/icons.js
  stories/link.js
  stories/pagination.js
  stories/popover.js
  stories/tab.js
  stories/tooltip.js
Labels: ready

#283 Update status labels styling
  components/statusLabel/StatusLabel.js
  components/statusLabel/theme.css
  stories/statusLabel.js
Labels: enhancement, ready

#284 Update/counter
  components/counter/Counter.js
  components/counter/theme.css
  stories/avatars.js
Labels: enhancement, ready

#291 Ensure the proper alignment of the input error message and icon
  components/input/Input.js
Labels: bug, ready

#286 Component/progress tracker
  components/index.js
  components/progressTracker/ProgressStep.js
  components/progressTracker/ProgressTracker.js
  components/progressTracker/index.js
  components/progressTracker/theme.css
  stories/progressTracker.js
Labels: new component, ready

#289 Send full event object down to the provided onchange handler
  components/input/Input.js
Labels: bug, ready

#292 Update/update packages
  package.json
Labels: package update, ready

#300 Put isDark function in utils
  components/island/Island.js
  components/island/IslandGroup.js
  components/section/Section.js
  components/utils/utils.js
Labels: enhancement, ready

#295 Add custom link and action option to Toasts
  components/toast/Toast.js
  components/toast/theme.css
  stories/toast.js
Labels: enhancement, ready
