Repository teamleadercrm/ui, pull requests merged in 2019-10, with the labels that each got.

#698 Link: `left` as the default value for `iconPlacement`
  CHANGELOG.md
  src/components/link/Link.js
Labels: enhancement, ready

#699 💄 Remove padding on the right of banner content
  CHANGELOG.md
  src/components/banner/Banner.js
  src/components/banner/theme.css
  stories/banners.js
Labels: bug, ready

#702 [AHOY-336] Checkbox - increase spacing between checkbox and label
  CHANGELOG.md
  src/components/checkbox/theme.css
Labels: enhancement, ready

#701 [AHOY-335] Radio button - increase spacing between radio and label
  CHANGELOG.md
  src/components/radio/theme.css
Labels: enhancement, ready

#700 [AHOY-337] Radio button - change default background color
  CHANGELOG.md
  src/components/radio/theme.css
Labels: enhancement, ready

#703 [AHOY-338] MenuItem add label & recycle caption
  CHANGELOG.md
  src/components/button/SplitButton.js
  src/components/menu/MenuItem.js
  src/components/menu/theme.css
  stories/datagrid.js
  stories/menu.js
  stories/popover.js
  stories/splitButton.js
  stories/widget.js
Labels: feature, ready

#704 Select: fix line-height
  CHANGELOG.md
  src/components/select/Select.js
Labels: bug, ready

#705 Release 0.31.0
  CHANGELOG.md
  package.json
Labels: ready, release

#706 Avatar: simplify the hashCode function logic
  src/components/avatar/Avatar.js
Labels: enhancement, ready

#708 🐛Don't pass boxProps to Avatar child components
  CHANGELOG.md
  src/components/avatar/Avatar.js
Labels: bug, ready

#709 Avatar: adjust the size of the small variant
  CHANGELOG.md
  src/components/avatar/theme.css
Labels: enhancement, ready

#710 Box: remove children from the boxProps list
  CHANGELOG.md
  src/components/box/boxProps.js
Labels: bug, ready

#711 Release 0.31.1
  CHANGELOG.md
  package.json
Labels: ready, release

#712 Link: add an outline effect to indicate focus state
  src/components/link/theme.css
Labels: enhancement, ready
