Repository teamleadercrm/ui, pull requests merged in 2019-11, with the labels that each got.

#716 DatePickerInput: render placeholder when selected date is not set
  src/components/datepicker/DatePickerInput.js
Labels: bug, ready

#717 Release 0.31.3
  CHANGELOG.md
  package.json
Labels: ready, release

#721 Menu item: allow anchor tags
  CHANGELOG.md
  src/components/menu/MenuItem.js
  src/components/menu/theme.css
  stories/menu.js
Labels: feature, ready

#722 Typography: Heading5
  CHANGELOG.md
  package.json
  src/components/typography/index.js
  src/index.js
  stories/typography.js
Labels: new component, ready

#724 Typography: TextBodyCompact
  CHANGELOG.md
  package.json
  src/components/typography/index.js
  src/index.js
  stories/typography.js
Labels: new component, ready

#725 Release 0.31.4
  CHANGELOG.md
  package.json
Labels: ready, release

#727 Fix _blank click on core
  CHANGELOG.md
  src/components/menu/MenuItem.js
  src/components/menu/theme.css
Labels: bug, enhancement, ready

#729 Release 0.31.5
  CHANGELOG.md
  package.json
Labels: ready, release

#728 📝 Add dependency updates to default changelog headers
  README.md
Labels: enhancement, maintenance, ready
