Repository teamleadercrm/ui, pull requests merged in 2019-04, with the labels that each got.

#576 AvatarStack: fix sizes
  CHANGELOG.md
  src/components/avatar/AvatarStack.js
  src/components/avatar/theme.css
  stories/avatars.js
Labels: maintenance, ready

#578 AvatarStack: fix overflowAmount display
  CHANGELOG.md
  src/components/avatar/AvatarStack.js
Labels: maintenance, ready

#580 Maintenance: move disabled on link with text
  stories/link.js
Labels: maintenance, ready

#581 New component: Widget
  .storybook/config.js
  CHANGELOG.md
  src/components/widget/Body.js
  src/components/widget/Footer.js
  src/components/widget/Header.js
  src/components/widget/Widget.js
  src/components/widget/index.js
  src/index.js
  stories/widget.js
Labels: new component, ready

#583 Maintenance: change bordered prop DataGrid
  CHANGELOG.md
  src/components/datagrid/theme.css
Labels: maintenance, ready

#566 New component: TimerPulser
  CHANGELOG.md
  src/components/timerPulser/TimerPulser.js
  src/components/timerPulser/index.js
  src/components/timerPulser/theme.css
  src/index.js
  stories/timerPulser.js
Labels: new component, ready

#585 Release 0.24.5
  CHANGELOG.md
  package.json
Labels: release

#587 Dialog: Remove resize magic and inner container
  CHANGELOG.md
  src/components/dialog/Dialog.js
  src/components/dialog/theme.css
  stories/dialogs.js
Labels: maintenance, ready

#588 AvatarInitials: fix width and height
  CHANGELOG.md
  src/components/avatar/theme.css
Labels: maintenance, ready

#584 DatePicker: Add bordered prop
  CHANGELOG.md
  src/components/datepicker/DatePicker.js
  src/components/datepicker/DatePickerInput.js
  src/components/datepicker/DatePickerRange.js
  src/components/datepicker/theme.css
  stories/datePicker.js
Labels: enhancement, ready

#593 Labels: Change alignment
  CHANGELOG.md
  src/components/checkbox/theme.css
  src/components/radio/theme.css
  src/components/toggle/theme.css
Labels: maintenance, ready

#590 Stories: Widget changes
  stories/widget.js
Labels: maintenance, ready

#589 Storybook maintenance
  stories/avatars.js
  stories/badge.js
  stories/box.js
  stories/button.js
  stories/buttonGroup.js
  stories/checkbox.js
  stories/datagrid.js
  stories/datePicker.js
  stories/dialogs.js
  stories/input.js
  stories/label.js
  stories/link.js
  stories/menu.js
  stories/playground.js
  stories/popover.js
  stories/tab.js
  stories/toast.js
  stories/widget.js
Labels: maintenance

#591 Stories: add DataGrid in Dialog
  stories/playground.js
  stories/static/data/datagrid.js
Labels: enhancement, ready

#595 Passport: rename the 'links' prop to 'lineItems'
  CHANGELOG.md
  src/components/passport/Passport.js
  stories/passport.js
Labels: enhancement, ready

#596 Release 0.25.0
  CHANGELOG.md
  package.json
Labels: ready, release

#597 Popover: maxWidth
  CHANGELOG.md
  src/components/popover/Popover.js
  stories/popover.js
Labels: feature, ready

#598 Fix icons version
  package.json
Labels: maintenance, ready
