Repository teamleadercrm/ui, pull requests merged in 2019-09, with the labels that each got.

#673 Box: add textAlign prop
  CHANGELOG.md
  src/components/box/Box.js
  src/components/box/boxProps.js
  src/components/box/theme.css
  stories/box.js
Labels: feature, ready

#674 Update ui-illustrations
  CHANGELOG.md
  package.json
  stories/illustrations.js
Labels: dependencies, ready

#675 Release 0.28.1
  CHANGELOG.md
  package.json
Labels: ready, release

#676 Avatar: hero size
  CHANGELOG.md
  src/components/avatar/AvatarImage.js
  src/components/avatar/AvatarInitials.js
  src/components/avatar/AvatarStack.js
  src/components/avatar/theme.css
  stories/avatars.js
Labels: feature, ready

#678 Avatar: refactor & add an editable state
  CHANGELOG.md
  src/components/avatar/Avatar.js
  src/components/avatar/AvatarImage.js
  src/components/avatar/AvatarInitials.js
  src/components/avatar/AvatarOverlay.js
  src/components/avatar/index.js
  src/components/avatar/theme.css
  src/components/passport/EmptyPassport.js
  src/components/passport/Passport.js
  src/index.js
  stories/avatars.js
  stories/menu.js
  stories/passport.js
  stories/select.js
Labels: feature, ready

#681 Box: borders
  CHANGELOG.md
  src/components/box/Box.js
  src/components/box/boxProps.js
  stories/box.js
Labels: feature, ready

#682 Release 0.29.0
  CHANGELOG.md
  package.json
Labels: ready, release

#680 Dependencies: Replace postcss-cssnext
  CHANGELOG.md
  package.json
  postcss.config.js
Labels: maintenance

#683 Release 0.30.0
  CHANGELOG.md
  package.json
Labels: ready, release

#684 🐛 Fix: custom properties and colors
  CHANGELOG.md
  package.json
  postcss.config.js
  src/components/badge/theme.css
Labels: bug, ready

#685 Release 0.30.1
  CHANGELOG.md
  package.json
Labels: ready, release

#686 Dependency update @teamleader/ui-typography
  .storybook/config.js
  CHANGELOG.md
  package.json
  src/components/select/Select.js
Labels: dependencies, ready

#687 Typography: overflow ellipsis
  CHANGELOG.md
  src/components/typography/Text.js
  stories/typography.js
Labels: feature, ready

#688 Release 0.30.2
  CHANGELOG.md
  package.json
Labels: ready, release

#689 Select: fix line-height issue
  CHANGELOG.md
  src/components/select/Select.js
Labels: ready

#690 StatusLabel: padding adjustment
  CHANGELOG.md
  src/components/statusLabel/StatusLabel.js
  src/components/statusLabel/theme.css
Labels: enhancement, ready

#691 Counter: enhancements
  CHANGELOG.md
  src/components/counter/Counter.js
  src/components/counter/theme.css
  stories/counter.js
Labels: enhancement, ready

#694 Link: inverse underline
  CHANGELOG.md
  src/components/link/Link.js
  src/components/link/theme.css
  stories/link.js
Labels: feature, ready

#695 Release 0.30.3
  CHANGELOG.md
  package.json
Labels: ready, release

#696 Counter: decrease horizontal padding
  CHANGELOG.md
  src/components/counter/theme.css
Labels: enhancement, ready

#697 Button & IconButton: base on Box component
  CHANGELOG.md
  src/components/button/Button.js
  src/components/button/IconButton.js
  src/components/button/theme.css
Labels: enhancement, ready
