Repository teamleadercrm/ui, pull requests merged in 2019-01, with the labels that each got.

#485 [TU-235] Popover: Use ReactResizeDetector throttling
  src/components/popover/Popover.js
Labels: maintenance, ready

#473 [TU-219] DataGrid: make row fully clickable
  CHANGELOG.md
  src/components/datagrid/BodyRow.js
  src/components/datagrid/DataGrid.js
  src/components/datagrid/theme.css
  stories/datagrid.js
Labels: feature, ready

#488 [TU-227] DataGrid: use Array.isArray instead of isArray from node
  CHANGELOG.md
  src/components/datagrid/DataGrid.js
Labels: maintenance, ready

#491 Popover: Fix update of dimension and position
  src/components/popover/Popover.js
Labels: bug, ready

#487 [TU-232] Link: disabled state
  CHANGELOG.md
  src/components/link/Link.js
  src/components/link/theme.css
  stories/link.js
Labels: feature, ready

#489 [TU-228] LoadingBar: change default 'tint' to 'normal'
  CHANGELOG.md
  src/components/loadingBar/LoadingBar.js
Labels: maintenance, ready

#492 Release/0.19.5
  CHANGELOG.md
  package.json
Labels: ready, release

#493 [TU-248] Message button placement
  CHANGELOG.md
  src/components/message/Message.js
  src/components/message/theme.css
Labels: enhancement, ready

#495 [TU-261] Popover: cross browser height fix
  CHANGELOG.md
  src/components/popover/Popover.js
  src/components/scrollContainer/ScrollContainer.js
  src/components/scrollContainer/theme.css
Labels: bug, ready

#496 Release/0.19.6
  CHANGELOG.md
  package.json
Labels: ready, release

#498 [TU-261] Popover: set dimensions via CSS fix
  CHANGELOG.md
  src/components/popover/Popover.js
Labels: bug, ready

#499 Release/0.19.7
  CHANGELOG.md
  package.json
Labels: ready, release

#497 Explicit main
  CHANGELOG.md
  package.json
Labels: enhancement, ready

#494 [TU-191] Input: directly provide width
  CHANGELOG.md
  src/components/input/SingleLineInputBase.js
  stories/input.js
Labels: feature, question, ready

#501 Release 0.19.8
  CHANGELOG.md
  package.json
Labels: ready, release

#502 Maintenance: validation - clean up obsolete styles
  src/components/datepicker/theme.css
  src/components/input/theme.css
  src/components/select/theme.css
Labels: maintenance, ready

#500 [TU-256] QTip: overlay event handler props & closed becomes active
  CHANGELOG.md
  src/components/qTip/QTip.js
  src/components/qTip/theme.css
  stories/qTip.js
Labels: enhancement, ready

#503 [FIX] Merge passed inputProps with internal inputProps in DatePickerInput
  CHANGELOG.md
  src/components/datepicker/DatePickerInput.js
Labels: bug, ready

#504 [TU-129] Input: implement warning & refactor error
  CHANGELOG.md
  src/components/input/Input.js
  src/components/input/InputBase.js
  src/components/input/SingleLineInputBase.js
  src/components/input/Textarea.js
  src/components/input/theme.css
  src/components/validationText/ValidationText.js
  src/components/validationText/WarningText.js
  src/components/validationText/index.js
  stories/input.js
Labels: feature, ready

#505 DatePickerInput & DatePickerInputRange: warning state
  CHANGELOG.md
  src/components/datepicker/DatePickerInput.js
  src/components/datepicker/DatePickerInputRange.js
  src/components/datepicker/theme.css
  stories/datePicker.js
Labels: feature, ready

#508 [TU-270] Popover: fix flexbox behavior
  CHANGELOG.md
  src/components/popover/Popover.js
  src/components/popover/theme.css
  src/components/scrollContainer/theme.css
Labels: bug, ready

#509 Release 0.20.0
  CHANGELOG.md
  package.json
Labels: ready, release

#510 [TU-275] Select: directly provide width
  CHANGELOG.md
  src/components/select/Select.js
  stories/select.js
Labels: feature, ready

#513 Bugfix Popover scroll container
  CHANGELOG.md
  src/components/popover/theme.css
  src/components/scrollContainer/ScrollContainer.js
Labels: WIP, bug

#515 Use a div as the element for the toast label/children wrapper
  CHANGELOG.md
  src/components/toast/Toast.js
Labels: enhancement

#516 Box: overflow props
  CHANGELOG.md
  src/components/box/Box.js
  src/components/box/boxProps.js
Labels: feature, ready

#517 Popover: drop header & footer, use children instead
  CHANGELOG.md
  src/components/popover/Popover.js
  stories/popover.js
Labels: feature, ready

#518 Release 0.21.0
  CHANGELOG.md
  package.json
Labels: ready, release

#521 Box: spread the style prop
  CHANGELOG.md
  src/components/box/Box.js
Labels: bug, ready

#522 Release 0.21.1
  CHANGELOG.md
  package.json
Labels: ready, release
