Repository teamleadercrm/ui, pull requests merged in 2019-02, with the labels that each got.

#524 [TU-278] Select: selected option state should overrule hover state
  CHANGELOG.md
  src/components/select/Select.js
Labels: bug, ready

#523 Box: check if flexGrow, flexShrink & order are a numbers
  CHANGELOG.md
  src/components/box/Box.js
Labels: bug, ready

#525 [TU-237 & TU-236] Popover: extract getMaxHeight calculation & use createRef
  CHANGELOG.md
  src/components/popover/Popover.js
  src/components/popover/sizeCalculation.js
Labels: maintenance, ready

#526 Storybook: add an illustration overview (ui-illustrations)
  stories/illustrations.js
Labels: enhancement, ready, storybook

#527 Fix: AsyncSelect refetch options when handler changed
  CHANGELOG.md
  src/components/select/AsyncSelect.js
Labels: bug, ready

#528 Release 0.21.2
  CHANGELOG.md
  package.json
Labels: ready, release

#529 Label: merge child props with custom props
  CHANGELOG.md
  src/components/label/Label.js
Labels: enhancement, ready

#530 [TU-280] RadioButton: make sure it doesn't get squeezed
  CHANGELOG.md
  src/components/radio/theme.css
Labels: enhancement, ready

#531 [TU-187 & TU-189] Select: dropdown menu portal possibility
  CHANGELOG.md
  src/components/select/Select.js
  stories/playground.js
Labels: bug, ready

#534 Z indexes reviewed
  CHANGELOG.md
  src/components/dialog/theme.css
  src/components/menu/theme.css
  src/components/overlay/theme.css
  src/components/popover/Popover.js
  src/components/popover/theme.css
  src/components/qTip/theme.css
  src/components/select/Select.js
  src/components/toast/theme.css
  src/components/tooltip/theme.css
  stories/playground.js
Labels: maintenance, ready
