Repository teamleadercrm/ui, pull requests merged in 2019-03, with the labels that each got.

#537 [AHOY-286] Input elements: innerRef
  CHANGELOG.md
  src/components/input/InputBase.js
  stories/playground.js
Labels: feature, ready

#538 Release 0.22.0
  CHANGELOG.md
  package.json
Labels: ready, release

#539 Numeric input: disable tabindex for the spinner controls
  CHANGELOG.md
  src/components/input/NumericInput.js
Labels: enhancement, ready

#536 [AHOY-285] Removed Arrow From Popover
  src/components/popover/Popover.js
  src/components/popover/positionCalculation.js
  src/components/popover/theme.css
  stories/popover.js
Labels: enhancement, ready

#540 Icon: vertical alignment fix
  CHANGELOG.md
  src/components/datepicker/theme.css
  src/components/icon/Icon.js
  src/components/input/theme.css
  src/components/link/theme.css
  src/components/menu/theme.css
  src/components/passport/Passport.js
  src/components/validationText/ErrorText.js
  src/components/validationText/WarningText.js
  stories/icons.js
Labels: enhancement, ready

#535 [AHOY-218] Date picker - refactor based on Input & Popover
  CHANGELOG.md
  src/components/datepicker/DatePickerInput.js
  src/components/datepicker/localeUtils.js
  src/components/datepicker/theme.css
  src/components/popover/Popover.js
  stories/datePicker.js
  stories/playground.js
  stories/static/data/languages.js
Labels: enhancement, feature, ready

#541 Input & Select: validation success
  CHANGELOG.md
  src/components/input/SingleLineInputBase.js
  src/components/input/Textarea.js
  src/components/input/theme.css
  src/components/select/Select.js
  src/components/validationText/SuccessText.js
  src/components/validationText/ValidationText.js
  src/components/validationText/index.js
  stories/input.js
  stories/select.js
Labels: feature, ready

#542 Maintenance/remove compose
  CHANGELOG.md
  package.json
  src/components/avatar/AvatarStack.js
  src/components/avatar/theme.css
  src/components/button/Button.js
  src/components/button/IconButton.js
  src/components/button/theme.css
  src/components/counter/Counter.js
  src/components/counter/theme.css
  src/components/datagrid/Cell.js
  src/components/datagrid/theme.css
  src/components/datepicker/DatePicker.js
  src/components/datepicker/DatePickerInputRange.js
  src/components/datepicker/DatePickerRange.js
  src/components/datepicker/theme.css
  src/components/dialog/DialogBase.js
  src/components/dialog/theme.css
  src/components/link/Link.js
  src/components/link/theme.css
  src/components/menu/Menu.js
  src/components/menu/theme.css
  src/components/popover/Popover.js
  src/components/popover/theme.css
  src/components/select/Select.js
  src/components/select/theme.css
  src/components/statusLabel/StatusLabel.js
  src/components/statusLabel/theme.css
  src/components/tag/Tag.js
  src/components/tag/theme.css
  src/components/toast/Toast.js
  src/components/toast/theme.css
  src/components/tooltip/Tooltip.js
  src/components/tooltip/theme.css
Labels: maintenance, ready

#545 [AHOY-292] Link: change margin between link and icon to 6px
  CHANGELOG.md
  src/components/link/theme.css
Labels: enhancement, ready

#543 Fix datepicker days
  src/components/datepicker/localeUtils.js
Labels: bug, ready

#544 [AHOY-221] Replace ref with createRef
  CHANGELOG.md
  src/components/badge/Badge.js
  src/components/box/Box.js
  src/components/checkbox/Checkbox.js
  src/components/dialog/Dialog.js
  src/components/menu/Menu.js
  src/components/radio/RadioButton.js
  src/components/tab/IconTab.js
  src/components/tab/TitleTab.js
  src/components/toggle/Toggle.js
Labels: maintenance, ready

#546 Release 0.23.0
  CHANGELOG.md
  package.json
Labels: ready, release

#547 Bugfix: refs errors
  CHANGELOG.md
  src/components/badge/Badge.js
  src/components/tab/IconTab.js
  src/components/tab/TitleTab.js
Labels: bug, ready

#548 Release 0.23.1
  CHANGELOG.md
  package.json
Labels: ready, release

#549 Maintenance: fix console warnings & cleanup unused code
  src/components/button/Button.js
  src/components/dialog/Dialog.js
  src/components/input/NumericInput.js
  src/components/link/Link.js
  src/components/validationText/ValidationText.js
  stories/checkbox.js
Labels: maintenance, ready

#550 Select: adjust alignment headers
  CHANGELOG.md
  src/components/select/Select.js
Labels: enhancement, ready

#552 Move luxon from devDependencies to dependencies
  CHANGELOG.md
  package.json
Labels: package update, ready

#551 Menu & MenuItem: refactor & restyle according new design
  CHANGELOG.md
  src/components/menu/Menu.js
  src/components/menu/MenuItem.js
  src/components/menu/MenuTitle.js
  src/components/menu/index.js
  src/components/menu/theme.css
  src/index.js
  stories/menu.js
  stories/popover.js
Labels: enhancement, maintenance, ready

#555 Remove white border in popover
  CHANGELOG.md
  src/components/popover/theme.css
Labels: maintenance, ready

#556 TimeInput component
  CHANGELOG.md
  package.json
  src/components/input/TimeInput.js
  src/components/input/index.js
  src/index.js
  stories/input.js
Labels: new component, ready

#553 Badge: refactor using our own Icon component
  CHANGELOG.md
  src/components/badge/Badge.js
  src/components/badge/theme.css
Labels: maintenance, ready

#557 Release 0.24.0
  CHANGELOG.md
  package.json
Labels: ready, release

#558 🚸 Make sure user can't enter invalid time
  CHANGELOG.md
  src/components/input/TimeInput.js
Labels: feature, ready

#559 IE11: some fixes for this lovely browser
  CHANGELOG.md
  src/components/popover/Popover.js
  src/components/radio/theme.css
Labels: bug, ready

#561 Fix: disabled and read-only on ie11
  CHANGELOG.md
  src/components/input/theme.css
Labels: bug, ready

#562 Fix resize checkbox
  CHANGELOG.md
  src/components/checkbox/theme.css
Labels: maintenance, ready

#563 Release 0.24.1
  CHANGELOG.md
  package.json
Labels: ready, release

#564 DatePickerInput: prevent activating Popover when Input is read only
  CHANGELOG.md
  src/components/datepicker/DatePickerInput.js
Labels: enhancement, ready

#565 Release 0.24.2
  CHANGELOG.md
  package.json
Labels: ready, release

#567 Fix disabled and readOnly of TimeInput
  CHANGELOG.md
  src/components/input/TimeInput.js
Labels: maintenance, ready

#569 Fix alignment in label
  CHANGELOG.md
  src/components/label/Label.js
Labels: maintenance, ready

#568 AvatarName: new component
  CHANGELOG.md
  src/components/avatar/Avatar.js
  src/components/avatar/AvatarInitials.js
  src/components/avatar/AvatarStack.js
  src/components/avatar/index.js
  src/components/avatar/theme.css
  src/index.js
  stories/avatars.js
Labels: new component, ready

#570 Release 0.24.3
  CHANGELOG.md
  package.json
Labels: ready, release

#572 🐛 Fix missing locale values
  src/components/datepicker/localeUtils.js
Labels: bug, ready

#575 Fix: AvatarInitials set letter-spacing to 0
  CHANGELOG.md
  src/components/avatar/theme.css
Labels: maintenance, ready

#579 Popover: add minWidth prop
  CHANGELOG.md
  src/components/popover/Popover.js
  stories/popover.js
Labels: enhancement, ready

#577 AvatarInitials: center initials with flexbox instead of paddings
  CHANGELOG.md
  src/components/avatar/theme.css
Labels: maintenance, ready
