Repository teamleadercrm/ui, pull requests merged in 2019-07, with the labels that each got.

#617 Remove dependency: imports-loader
  CHANGELOG.md
  package.json
Labels: dependencies, ready

#620 Maintenance: remove the react-hot-loader dependency
  .babelrc
  package.json
Labels: dependencies, ready

#621 Maintenance: upgrade all PostCSS dependencies
  package.json
Labels: dependencies, ready

#626 AvatarInitials: set a default color value
  CHANGELOG.md
  src/components/avatar/AvatarInitials.js
Labels: enhancement, ready

#625 Avatar: use display flex instead of inline-block
  CHANGELOG.md
  src/components/avatar/theme.css
Labels: enhancement, ready

#627 ProgressTracker: clickable status bullet only
  CHANGELOG.md
  src/components/progressTracker/ProgressStep.js
  src/components/progressTracker/theme.css
Labels: enhancement, ready

#629 New SplitButton component
  CHANGELOG.md
  src/components/button/SplitButton.js
  src/components/button/index.js
  src/index.js
  stories/splitButton.js
Labels: new component, ready

#633 Release 0.27.2
  CHANGELOG.md
  package.json
Labels: ready, release

#637 AdvancedCollapsible
  CHANGELOG.md
  src/components/advancedCollapsible/AdvancedCollapsible.js
  src/components/advancedCollapsible/index.js
  src/components/advancedCollapsible/theme.css
  src/index.js
  stories/advancedCollapsible.js
Labels: new component, ready

#638 Remove dependency: url-loader
  CHANGELOG.md
  package.json
Labels: dependencies, maintenance, ready

#642 Release 0.27.3
  CHANGELOG.md
  package.json
Labels: ready, release

#649 Fix loading spinner position
  CHANGELOG.md
  src/components/button/theme.css
Labels: bug, ready

#651 Release 0.27.4
  CHANGELOG.md
  package.json
Labels: ready, release
