Repository teamleadercrm/ui, pull requests merged in 2019-05, with the labels that each got.

#600 [AHOY-288] Box: background color & tint
  CHANGELOG.md
  src/components/box/Box.js
  src/components/box/theme.css
  stories/box.js
Labels: feature, ready

#601 [AHOY-303] Input/Textarea: separate validation message from validation border
  CHANGELOG.md
  src/components/input/SingleLineInputBase.js
  src/components/input/Textarea.js
  src/components/validationText/ValidationText.js
Labels: enhancement, ready

#599 [AHOY-302] Dialog: scrollable content
  CHANGELOG.md
  src/components/dialog/Dialog.js
  src/components/dialog/DialogBase.js
  stories/dialogs.js
  stories/playground.js
Labels: feature, ready

#602 Center the icon better in the banners
  CHANGELOG.md
  src/components/banner/theme.css
Labels: enhancement

#603 Release 0.26.0
  CHANGELOG.md
  package.json
Labels: ready, release

#605 ⬆️ Upgrade: Storybook 5
  .storybook/addons.js
  .storybook/config.js
  .storybook/webpack.config.js
  package.json
Labels: enhancement, package update, storybook
