Repository teamleadercrm/ui, pull requests merged in 2019-12, with the labels that each got.

#730 ✨Tooltip: delayed enter and new onTooltipEnter prop
  CHANGELOG.md
  src/components/tooltip/Tooltip.js
Labels: enhancement, feature, ready

#731 🏗Maintenance: switch to yarn
  .gitignore
  .npmrc
  CHANGELOG.md
  README.md
  package.json
  yarn.lock
Labels: enhancement, maintenance, ready

#732 Release/0.31.6
  CHANGELOG.md
  package.json
Labels: release

#736 Storybook: remove custom file-loader config
  .storybook/webpack.config.js
  CHANGELOG.md
Labels: maintenance, ready

#735 Avatar: anonymous user
  CHANGELOG.md
  src/components/avatar/Avatar.js
  src/components/avatar/AvatarAdd.js
  src/components/avatar/AvatarAnonymous.js
  src/components/avatar/AvatarImage.js
  src/components/avatar/AvatarInitials.js
  src/components/avatar/theme.css
  stories/avatars.js
Labels: feature, ready

#737 Box: border radius
  CHANGELOG.md
  src/components/box/Box.js
  src/components/box/boxProps.js
  stories/box.js
Labels: feature, ready

#738 Avatar: hover & selected state
  CHANGELOG.md
  src/components/avatar/Avatar.js
  src/components/avatar/AvatarStack.js
  src/components/avatar/theme.css
  stories/avatars.js
Labels: feature, ready

#739 Release 0.33.0
  CHANGELOG.md
  package.json
Labels: ready, release

#746 ⬆️ upgrade all @babel packages
  package.json
  yarn.lock
Labels: dependencies, ready

#745 Fix/toggle component
  CHANGELOG.md
  src/components/toggle/Toggle.js
  src/components/toggle/toggle.stories.js
Labels: enhancement, ready

#750 Release/0.34.0
  CHANGELOG.md
  package.json
Labels: release

#755 🔧 Don't require library users to use postcss
  .babelrc
  .gitignore
  CHANGELOG.md
  index.d.ts
  package.json
  rollup.config.js
  yarn.lock
Labels: enhancement, ready

#756 NumericInput: refactor and extend spinner
  CHANGELOG.md
  src/components/input/NumericInput.js
  src/components/input/input.stories.js
  src/components/input/theme.css
Labels: feature, ready

#759 Input & Select: focus state should not overrule any other state
  CHANGELOG.md
  src/components/input/theme.css
  src/components/select/Select.js
Labels: enhancement, ready

#760 Release 0.35.0
  CHANGELOG.md
  package.json
Labels: ready, release

#761 DataGrid: 12 column grid
  CHANGELOG.md
  src/components/datagrid/Cell.js
  src/components/datagrid/datagrid.stories.js
  src/components/datagrid/theme.css
Labels: feature, ready

#765 ⬆️ upgrade @babel packages
  package.json
  yarn.lock
Labels: dependencies

#768 Revert "🔧 Don't require library users to use postcss"
  .babelrc
  .gitignore
  CHANGELOG.md
  package.json
  rollup.config.js
  yarn.lock
Labels: ready

#772 🔧 Add a deploy file that can be used by teamleader's ci-system
  CHANGELOG.md
  ci/deploy-storybook.yml
Labels: enhancement, ready

#773 release/0.35.2
  CHANGELOG.md
  package.json
Labels: release

#774 🏷 include the types file
  CHANGELOG.md
  package.json
Labels: enhancement, ready

#775 release/0.35.3
  CHANGELOG.md
  package.json
Labels: release
