Repository teamleadercrm/ui, pull requests merged in 2019-08, with the labels that each got.

#653 🐛 Make display overwritable for Label
  src/components/label/Label.js
  src/components/label/theme.css
Labels: bug, ready

#654 Release 0.27.5
  CHANGELOG.md
  package.json
Labels: ready, release

#656 Destructure other props in avatar initials
  CHANGELOG.md
  src/components/avatar/AvatarInitials.js
Labels: bug

#657 Release 0.27.6
  CHANGELOG.md
  package.json
Labels: release

#659 Release 0.27.7
  CHANGELOG.md
  package.json
Labels: ready, release

#660 Fix: include postcss.config.js when installing as dependency
  CHANGELOG.md
  package.json
Labels: enhancement, maintenance, ready

#664 Don't change the date when the date is disabled
  CHANGELOG.md
  src/components/datepicker/DatePicker.js
  src/components/datepicker/DatePickerRange.js
Labels: enhancement, ready

#666 🐛Fix console errors for Menu component
  CHANGELOG.md
  src/components/menu/IconMenu.js
  src/components/menu/Menu.js
Labels: bug, ready

#667 Checkbox: apply 'position: absolute;' to the input element
  CHANGELOG.md
  src/components/checkbox/theme.css
Labels: enhancement, ready

#668 DataGrid - HeaderCell: adjust to new design
  CHANGELOG.md
  src/components/datagrid/HeaderCell.js
  src/components/datagrid/theme.css
Labels: enhancement, ready

#669 AvatarInitials: make sure the text is not selectable
  CHANGELOG.md
  src/components/avatar/theme.css
Labels: enhancement, ready

#670 Avatar: AvatarImage or AvatarInitials
  CHANGELOG.md
  src/components/avatar/Avatar.js
  src/components/avatar/AvatarImage.js
  src/components/avatar/index.js
  src/components/avatar/theme.css
  src/components/passport/EmptyPassport.js
  src/components/passport/Passport.js
  src/index.js
  stories/avatars.js
  stories/menu.js
  stories/select.js
  stories/static/data/avatar.js
Labels: new component, ready

#671 Release 0.28.0
  CHANGELOG.md
  package.json
Labels: ready, release

#672 Select: camelCase font smoothing emotion css props
  CHANGELOG.md
  src/components/select/Select.js
Labels: maintenance, ready
