Repository teamleadercrm/ui, pull requests merged in 2019-06, with the labels that each got.

#606 Storybook upgrade: follow up
  .storybook/addons.js
  .storybook/config.js
  .storybook/teamleaderTheme.js
  package.json
  stories/banners.js
Labels: enhancement, maintenance, ready, storybook

#607 ProgressTracker: adjust styling make clickable
  CHANGELOG.md
  src/components/progressTracker/ProgressStep.js
  src/components/progressTracker/theme.css
  stories/progressTracker.js
Labels: enhancement, feature, ready

#608 Release 0.27.0
  CHANGELOG.md
  package.json
Labels: ready, release

#609 [ENHANCEMENT] Refactor build flow and make it tree shakeable
  .babelrc
  .eslintrc
  .gitignore
  .npmignore
  CHANGELOG.md
  gulpfile.js
  package.json
  postcss.config.js
  stories/icons.js
  stories/select.js
  stories/widget.js
Labels: enhancement

#610 Avatar: large size variation
  CHANGELOG.md
  src/components/avatar/Avatar.js
  src/components/avatar/AvatarInitials.js
  src/components/avatar/AvatarStack.js
  src/components/avatar/theme.css
  stories/avatars.js
Labels: feature, ready

#611 Bullet: large size variation
  CHANGELOG.md
  src/components/bullet/Bullet.js
  src/components/bullet/theme.css
  stories/bullet.js
Labels: feature, ready

#612 Counter: change font weight from 'black' to 'bold'
  CHANGELOG.md
  src/components/counter/theme.css
Labels: enhancement, ready

#613 Release 0.27.1
  CHANGELOG.md
  package.json
Labels: ready, release
