Repository teamleadercrm/ui, pull requests merged in 2020-07, with the labels that each got.

#1200 Toggle: use consistent margins
  CHANGELOG.md
  src/components/toggle/theme.css
Labels: enhancement, ready

#1205 WysiwygEditor: onFocus/onBlur fixes
  CHANGELOG.md
  src/components/wysiwygEditor/LinkOptions.js
  src/components/wysiwygEditor/WysiwygEditor.js
Labels: bug, ready

#1204 Upgrade all babel dependencies
  package.json
  yarn.lock
Labels: dependencies, ready

#1206 Release 0.48.2
  CHANGELOG.md
  package.json
Labels: ready, release

#1207 WysiwygEditor: Focus fixes
  CHANGELOG.md
  src/components/wysiwygEditor/LinkOptions.js
  src/components/wysiwygEditor/WysiwygEditor.js
Labels: bug, ready

#1208 Release 0.48.3
  CHANGELOG.md
  package.json
Labels: ready, release

#1211 Release/0.48.4
  CHANGELOG.md
  package.json
Labels: release

#1212 DatePicker: also check for the base french locale when formatting month names
  CHANGELOG.md
  src/components/datepicker/MonthPicker.js
Labels: bug, ready

#1213 Tabs: scroll to active tab
  CHANGELOG.md
  src/components/tab/TabGroup.js
  src/components/tab/TitleTab.js
  src/static/data/tab.js
Labels: enhancement, ready

#1214 Add figma urls
  src/components/checkbox/checkbox.stories.js
  src/components/radio/radio.stories.js
  src/components/toggle/toggle.stories.js
Labels: enhancement, ready, storybook

#1215 Release 0.48.5
  CHANGELOG.md
  package.json
Labels: ready, release

#1216 `DatePickerInput`: Add `openPickerOnFocus` prop
  src/components/datepicker/DatePickerInput.js
Labels: bug, ready

#1219 Release 0.48.6
  CHANGELOG.md
  package.json
Labels: ready, release

#1220 SilentBanner: full width by default & add inline prop
  CHANGELOG.md
  src/components/silentBanner/SilentBanner.js
  src/components/silentBanner/silentBanner.stories.js
Labels: breaking, feature, ready

#1221 SilentBanner: remove children's TextBody wrapper
  CHANGELOG.md
  src/components/silentBanner/SilentBanner.js
  src/components/silentBanner/silentBanner.stories.js
Labels: breaking, enhancement, ready

#1222 Release 1.0.0
  CHANGELOG.md
  package.json
Labels: breaking, ready, release

#1223 NumericInput: call onBlur when stepper buttons get blurred
  CHANGELOG.md
  src/components/input/NumericInput.js
Labels: bug, enhancement, ready

#1224 release/1.0.1
  CHANGELOG.md
  package.json
Labels: release

#1226 Add tabIndex property to date picker footer
  CHANGELOG.md
  src/components/datepicker/DatePickerInput.js
Labels: enhancement, ready

#1227 release/1.0.2
  CHANGELOG.md
  package.json
Labels: release

#1234 Upgrade all babel dependencies
  package.json
  yarn.lock
Labels: dependencies, ready

#1238 Storybook to 6.0.0-rc.15
  .babelrc
  .storybook/preview.js
  .storybook/stories/playground/zIndexes.stories.js
  package.json
  src/components/badge/badge.stories.js
  src/components/banner/banner.stories.js
  src/components/box/box.stories.js
  src/components/bullet/bullet.stories.js
  src/components/button/button.stories.js
  src/components/buttonGroup/buttonGroup.stories.js
  src/components/checkbox/checkbox.stories.js
  src/components/container/container.stories.js
  src/components/counter/counter.stories.js
  src/components/datagrid/datagrid.stories.js
  src/components/datepicker/datePicker.stories.js
  src/components/detailPage/detailPage.stories.js
  src/components/dialog/dialog.stories.js
  src/components/icon/icon.stories.js
  src/components/iconButton/iconButton.stories.js
  src/components/input/input.stories.js
  src/components/island/island.stories.js
  src/components/label/label.stories.js
  src/components/labelValuePair/labelPair.stories.js
  src/components/link/link.stories.js
  src/components/loadingBar/loadingBar.stories.js
  src/components/loadingMolecule/loadingMolecule.stories.js
  src/components/loadingSpinner/loadingSpinner.stories.js
  src/components/menu/menu.stories.js
  src/components/message/message.stories.js
  src/components/overviewPage/overviewPage.stories.js
  src/components/pagination/pagination.stories.js
  src/components/popover/popover.stories.js
  src/components/progressTracker/progressTracker.stories.js
  src/components/qTip/qTip.stories.js
  src/components/radio/radio.stories.js
  src/components/section/section.stories.js
  src/components/select/select.stories.js
  src/components/silentBanner/silentBanner.stories.js
  src/components/splitButton/splitButton.stories.js
  src/components/statusBullet/statusBullet.stories.js
  src/components/statusLabel/statusLabel.stories.js
  src/components/tag/tag.stories.js
  src/components/timer/timer.stories.js
  src/components/timerPulser/timerPulser.stories.js
  src/components/toggle/toggle.stories.js
  src/components/tooltip/tooltip.stories.js
  src/components/typography/typography.stories.js
  src/components/widget/widget.stories.js
  src/components/wysiwygEditor/wysiwygEditor.stories.js
  yarn.lock
Labels: maintenance, ready, storybook

#1239 Storybook 6: replace addon-info with addon-docs
  .storybook/components/propTable/PropTable.js
  .storybook/components/propTable/index.js
  .storybook/main.js
  .storybook/preview.js
  package.json
  src/components/advancedCollapsible/advancedCollapsible.stories.js
  src/components/avatar/avatar.stories.js
  src/components/badge/badge.stories.js
  src/components/banner/banner.stories.js
  src/components/box/box.stories.js
  src/components/bullet/bullet.stories.js
  src/components/button/button.stories.js
  src/components/buttonGroup/buttonGroup.stories.js
  src/components/checkbox/checkbox.stories.js
  src/components/container/container.stories.js
  src/components/counter/counter.stories.js
  src/components/datagrid/datagrid.stories.js
  src/components/datepicker/datePicker.stories.js
  src/components/detailPage/detailPage.stories.js
  src/components/dialog/dialog.stories.js
  src/components/emptyState/emptyState.stories.js
  src/components/icon/icon.stories.js
  src/components/iconButton/iconButton.stories.js
  src/components/input/input.stories.js
  src/components/island/island.stories.js
  src/components/label/label.stories.js
  src/components/labelValuePair/labelPair.stories.js
  src/components/link/link.stories.js
  src/components/loadingBar/loadingBar.stories.js
  src/components/loadingMolecule/loadingMolecule.stories.js
  src/components/loadingSpinner/loadingSpinner.stories.js
  src/components/menu/menu.stories.js
  src/components/message/message.stories.js
  src/components/overviewPage/overviewPage.stories.js
  src/components/pagination/pagination.stories.js
  src/components/passport/passport.stories.js
  src/components/popover/popover.stories.js
  src/components/progressTracker/progressTracker.stories.js
  src/components/qTip/qTip.stories.js
  src/components/radio/radio.stories.js
  src/components/scrollContainer/scrollContainer.stories.js
  src/components/section/section.stories.js
  src/components/select/select.stories.js
  src/components/silentBanner/silentBanner.stories.js
  src/components/splitButton/splitButton.stories.js
  src/components/statusBullet/statusBullet.stories.js
  src/components/statusLabel/statusLabel.stories.js
  src/components/tab/tab.stories.js
  src/components/tag/tag.stories.js
  src/components/timer/timer.stories.js
  src/components/timerPulser/timerPulser.stories.js
  src/components/toast/toast.stories.js
  src/components/toggle/toggle.stories.js
  src/components/tooltip/tooltip.stories.js
  src/components/typography/typography.stories.js
  src/components/widget/widget.stories.js
  src/components/wysiwygEditor/wysiwygEditor.stories.js
  yarn.lock
Labels: maintenance, ready, storybook

#1243 Storybook 6: replace Knobs addon with Controls part 1
  package.json
  src/components/advancedCollapsible/advancedCollapsible.stories.js
  src/components/badge/badge.stories.js
  src/components/bullet/bullet.stories.js
  src/components/button/button.stories.js
  src/components/buttonGroup/buttonGroup.stories.js
  src/components/checkbox/checkbox.stories.js
  src/components/container/container.stories.js
  src/components/counter/counter.stories.js
  src/components/emptyState/emptyState.stories.js
  src/components/iconButton/iconButton.stories.js
  src/components/island/island.stories.js
  src/components/island/islandGroup.stories.js
  src/components/loadingBar/loadingBar.stories.js
  src/components/loadingSpinner/loadingSpinner.stories.js
  src/components/pagination/pagination.stories.js
  src/components/section/section.stories.js
  src/components/statusBullet/statusBullet.stories.js
  src/components/statusLabel/statusLabel.stories.js
  src/components/timer/timer.stories.js
  src/components/timerPulser/timerPulser.stories.js
  src/components/widget/widget.stories.js
  src/components/wysiwygEditor/wysiwygEditor.stories.js
  yarn.lock
Labels: maintenance, ready, storybook
