Repository teamleadercrm/ui, pull requests merged in 2020-05, with the labels that each got.

#1077 Upgrade all babel dependencies
  CHANGELOG.md
  package.json
  yarn.lock
Labels: dependencies, ready

#1089 IslandGroup: Filter out non-valid elements before changing props
  CHANGELOG.md
  src/components/island/IslandGroup.js
Labels: bug, ready

#1090 Change minWidth setting to 180px
  CHANGELOG.md
  src/components/popover/Popover.js
Labels: ready

#1093 Release 0.42.9
  CHANGELOG.md
  package.json
Labels: ready, release

#1092 Text & Heading: multiline overflow
  CHANGELOG.md
  src/components/button/Button.js
  src/components/datagrid/HeaderCell.js
  src/components/detailPage/DetailPageHeader.js
  src/components/typography/Text.js
  src/components/typography/theme.css
  src/components/typography/typography.stories.js
Labels: feature, ready

#1094 Release 0.43.0
  CHANGELOG.md
  package.json
Labels: ready, release

#1095 LabelValuePair
  src/components/labelValuePair/Label.js
  src/components/labelValuePair/LabelValuePair.js
  src/components/labelValuePair/LabelValuePairGroup.js
  src/components/labelValuePair/Value.js
  src/components/labelValuePair/index.js
  src/components/labelValuePair/labelPair.stories.js
Labels: feature, new component, ready

#1096 Release 0.43.1
  CHANGELOG.md
  package.json
Labels: ready, release

#1098 🐛 Fix internationalisation in MonthPicker component
  CHANGELOG.md
  src/components/datepicker/DatePicker.js
  src/components/datepicker/MonthPicker.js
Labels: bug

#1099 Select: keep showing selected options
  CHANGELOG.md
  src/components/select/Select.js
  src/components/select/select.stories.js
Labels: enhancement, ready

#1101 Fix: WysiwygEditor auto height
  CHANGELOG.md
  src/components/wysiwygEditor/theme.css
Labels: bug, ready

#1102 Release 0.43.2
  CHANGELOG.md
  package.json
Labels: ready, release

#1104 EmptyState: add hidePointer prop
  CHANGELOG.md
  src/components/emptyState/EmptyState.js
  src/components/emptyState/emptyState.stories.js
Labels: enhancement, feature, ready

#1103 Add `inputClassName` prop on `WysiwygEditor`
  CHANGELOG.md
  src/components/wysiwygEditor/WysiwygEditor.js
Labels: ready

#1105 Release 0.43.3
  CHANGELOG.md
  package.json
Labels: ready, release

#1107 Fix: LabelValuePair and LabelValuePairGroup were not exported
  CHANGELOG.md
  src/index.js
Labels: bug

#1106 Fix: WysiwygEditor `LinkOptions` dialog z-index
  CHANGELOG.md
  src/components/wysiwygEditor/LinkOptions.js
Labels: bug, ready

#1108 Release/0.43.4
  CHANGELOG.md
  package.json
Labels: release

#1109 SilentBanner: component
  CHANGELOG.md
  src/components/silentBanner/SilentBanner.js
  src/components/silentBanner/index.js
  src/components/silentBanner/silentBanner.stories.js
  src/index.js
Labels: new component, ready

#1110 Release 0.43.5
  CHANGELOG.md
  package.json
Labels: ready, release

#1112 Silent banner/enhancements
  CHANGELOG.md
  src/components/silentBanner/SilentBanner.js
Labels: enhancement, ready

#1113 Release 0.43.6
  CHANGELOG.md
  package.json
Labels: ready, release

#1116 Container: use a larger breakpoint
  CHANGELOG.md
  src/components/container/theme.css
Labels: enhancement, ready

#1120 Downgrade react-select dependency to use 3.0.4
  package.json
  yarn.lock
Labels: bug, dependencies, ready

#1121 Release 0.43.7
  CHANGELOG.md
  package.json
Labels: ready, release

#1122 LabelValuePair: fix right alignment for multiline values
  CHANGELOG.md
  src/components/labelValuePair/LabelValuePair.js
Labels: enhancement, ready

#1129 Bump eslint from 6.8.0 to 7.1.0
  package.json
  yarn.lock
Labels: dependencies, ready

#1111 Update teal dark & darkest color values
  CHANGELOG.md
  package.json
  src/constants/colors.js
  yarn.lock
Labels: enhancement, ready

#1130 Release 0.44.0
  CHANGELOG.md
  package.json
Labels: breaking, ready, release

#1131 Toast: use teal dark as background color
  CHANGELOG.md
  src/components/toast/theme.css
Labels: maintenance, ready

#1135 Upgrade all babel dependencies
  CHANGELOG.md
  package.json
  yarn.lock
Labels: dependencies, maintenance, ready
