Repository teamleadercrm/ui, pull requests merged in 2020-09, with the labels that each got.

#1290 Add Edit-action for medium-sized Avatars (on hover)
  CHANGELOG.md
  src/components/avatar/AvatarImage.js
  src/components/avatar/AvatarInitials.js
  src/components/avatar/AvatarOverlay.js
  src/components/avatar/theme.css
Labels: enhancement, ready

#1291 Release 1.0.3
  CHANGELOG.md
  package.json
Labels: ready, release

#1292 [FIX] Make sure full height avatar overlays are rounded at the top
  CHANGELOG.md
  src/components/avatar/theme.css
Labels: enhancement, ready

#1296 [CHORE] Remove "@storybook/addon-docs" as Dependency, and add it as DevDependency
  CHANGELOG.md
  package.json
Labels: dependencies

#1297 Release/1.0.5
  CHANGELOG.md
  package.json
Labels: dependencies

#1298 [Chore] Bump draft-js
  CHANGELOG.md
  package.json
  yarn.lock
Labels: dependencies, ready

#1305 release/1.0.6
  CHANGELOG.md
  package.json
Labels: ready, release
