Repository teamleadercrm/ui, pull requests merged in 2020-03, with the labels that each got.

#896 Release 0.36.7
  CHANGELOG.md
  package.json
Labels: ready, release

#898 ♿️ Fallback to avatar initials when image not found
  src/components/avatar/Avatar.js
  src/components/avatar/AvatarImage.js
Labels: enhancement, ready

#899 ♻️ Render AvatarInitials without providing id
  src/components/avatar/Avatar.js
  src/components/avatar/AvatarInitials.js
  src/components/avatar/theme.css
Labels: enhancement, ready

#900 Storybook: group and re-arrange stories
  .storybook/preview.js
  .storybook/stories/illustrations.stories.js
  .storybook/stories/playground/dialogs.stories.js
  .storybook/stories/playground/forms.stories.js
  .storybook/stories/playground/zIndexes.stories.js
  .storybook/utils/index.js
  src/components/advancedCollapsible/advancedCollapsible.stories.js
  src/components/avatar/avatar.stories.js
  src/components/badge/badge.stories.js
  src/components/banner/banner.stories.js
  src/components/box/box.stories.js
  src/components/bullet/bullet.stories.js
  src/components/button/button.stories.js
  src/components/button/buttonGroup.stories.js
  src/components/button/iconButton.stories.js
  src/components/button/splitButton.stories.js
  src/components/checkbox/checkbox.stories.js
  src/components/counter/counter.stories.js
  src/components/datagrid/datagrid.stories.js
  src/components/datepicker/datePicker.stories.js
  src/components/dialog/dialog.stories.js
  src/components/icon/icon.stories.js
  src/components/input/input.stories.js
  src/components/island/island.stories.js
  src/components/label/label.stories.js
  src/components/link/link.stories.js
  src/components/loadingBar/loadingBar.stories.js
  src/components/loadingMolecule/loadingMolecule.stories.js
  src/components/loadingSpinner/loadingSpinner.stories.js
  src/components/menu/menu.stories.js
  src/components/message/message.stories.js
  src/components/pagination/pagination.stories.js
  src/components/passport/passport.stories.js
  src/components/popover/popover.stories.js
  src/components/progressTracker/progressTracker.stories.js
  src/components/qTip/qTip.stories.js
  src/components/radio/radio.stories.js
  src/components/scrollContainer/scrollContainer.stories.js
  src/components/section/section.stories.js
  src/components/select/select.stories.js
  src/components/statusBullet/statusBullet.stories.js
  src/components/statusLabel/statusLabel.stories.js
  src/components/tab/tab.stories.js
  src/components/tag/tag.stories.js
  src/components/timerPulser/timerPulser.stories.js
  src/components/toast/toast.stories.js
  src/components/toggle/toggle.stories.js
  src/components/tooltip/tooltip.stories.js
  src/components/typography/typography.stories.js
  src/components/widget/widget.stories.js
Labels: ready, storybook

#904 Storybook: theme modifications
  .storybook/components/propTable/PropTable.js
  .storybook/manager-head.html
  .storybook/manager.js
  .storybook/preview-head.html
  .storybook/preview.js
Labels: enhancement, ready, storybook

#905 Navigation: adjust submenu item styling
  .storybook/manager-head.html
Labels: enhancement, ready, storybook

#906 Release 0.36.8
  CHANGELOG.md
  package.json
Labels: ready, release

#907 🏷 Add looser typing
  CHANGELOG.md
  index.d.ts
Labels: enhancement

#909 Release/0.36.9
  CHANGELOG.md
  package.json
Labels: release

#911 Forward ref in `DialogBase.Body`
  CHANGELOG.md
  src/components/dialog/Body.js
Labels: ready

#910 Avatar: fix linting error which blocks the CI
  src/components/avatar/Avatar.js
Labels: bug, ready

#912 Release 0.36.10
  CHANGELOG.md
  package.json
Labels: ready, release

#914 Avatar: refactor [part 1]
  CHANGELOG.md
  src/components/avatar/Avatar.js
  src/components/avatar/AvatarAdd.js
  src/components/avatar/AvatarAnonymous.js
  src/components/avatar/AvatarImage.js
  src/components/avatar/AvatarInitials.js
  src/components/avatar/AvatarStack.js
  src/components/avatar/theme.css
Labels: enhancement, maintenance, ready

#915 Bump @teamleader/ui-illustrations from 0.0.25 to 0.0.26
  .storybook/stories/illustrations.stories.js
  package.json
  yarn.lock
Labels: dependencies, ready

#921 Island: use Box props instead off CSS styles
  CHANGELOG.md
  src/components/island/Island.js
  src/components/island/IslandGroup.js
  src/components/island/island.stories.js
  src/components/island/theme.css
Labels: enhancement, maintenance, ready

#925 Button: outline colors instead of inverse
  CHANGELOG.md
  src/components/button/Button.js
  src/components/button/button.stories.js
  src/components/button/theme.css
Labels: feature, ready

#927 Box: negative margins
  CHANGELOG.md
  src/components/box/Box.js
  src/components/box/box.stories.js
  src/components/box/theme.css
Labels: feature, ready

#931 Fix `SplitButton` event handler parameters
  CHANGELOG.md
  src/components/button/SplitButton.js
Labels: bug, ready

#932 Release 0.37.0
  CHANGELOG.md
  package.json
Labels: ready, release

#928 Link: badged
  CHANGELOG.md
  src/components/link/Link.js
  src/components/link/link.stories.js
  src/components/link/theme.css
Labels: feature, ready

#933 Avatar stack: overlapping avatars
  CHANGELOG.md
  src/components/avatar/Avatar.js
  src/components/avatar/AvatarStack.js
  src/components/avatar/avatar.stories.js
  src/components/avatar/theme.css
Labels: feature, ready

#934 Release 0.38.0
  CHANGELOG.md
  package.json
Labels: ready, release

#937 StatusLabel: refactor and apply lighter background colors
  CHANGELOG.md
  src/components/statusLabel/StatusLabel.js
  src/components/statusLabel/theme.css
Labels: enhancement, ready

#938 Avatar stack: change display max default value
  CHANGELOG.md
  src/components/avatar/AvatarStack.js
Labels: bug, ready

#939 Avatar stack: fix wrapper bounding box
  CHANGELOG.md
  src/components/avatar/AvatarStack.js
Labels: enhancement, ready

#940 Widget: update header height
  CHANGELOG.md
  src/components/widget/Body.js
  src/components/widget/Footer.js
  src/components/widget/Header.js
  src/components/widget/Widget.js
  src/components/widget/theme.css
  src/components/widget/widget.stories.js
Labels: enhancement, ready

#948 Release 0.39.0
  CHANGELOG.md
  package.json
Labels: ready, release

#949 AvatarStack: only render `+` sign when displayMax is greater than zero
  CHANGELOG.md
  src/components/avatar/AvatarStack.js
Labels: enhancement, ready

#953 Avatar: add AvatarTeam component
  CHANGELOG.md
  package.json
  src/components/avatar/Avatar.js
  src/components/avatar/AvatarTeam.js
  src/components/avatar/avatar.stories.js
  yarn.lock
Labels: feature, new component, ready

#961 Widget: Avoid error when a child is null
  CHANGELOG.md
  src/components/widget/Widget.js
Labels: bug

#962 Release 0.39.1
  CHANGELOG.md
  package.json
Labels: ready, release

#969 Typography: add UITextDisplay, UITextBody & UITextSmall
  CHANGELOG.md
  src/components/typography/index.js
  src/components/typography/typography.stories.js
  src/index.js
Labels: new component, ready

#968 Badge: remove hardcoded horizontal margin
  CHANGELOG.md
  src/components/badge/badge.stories.js
  src/components/badge/theme.css
Labels: enhancement, ready

#970 Status label: remove hardcoded margin
  CHANGELOG.md
  src/components/statusLabel/statusLabel.stories.js
  src/components/statusLabel/theme.css
Labels: enhancement, ready

#971 Fix: Don't limit onClick on BodyRow children
  CHANGELOG.md
  src/components/datagrid/BodyRow.js
  src/components/datagrid/datagrid.stories.js
Labels: bug, ready

#973 Release 0.40.0
  CHANGELOG.md
  package.json
Labels: ready, release
