Repository teamleadercrm/ui, pull requests merged in 2020-12, with the labels that each got.

#1361 Dialog: remove redundant wrapper in dialog rendering implementation
  CHANGELOG.md
  src/components/dialog/DialogBase.js
Labels: bug, ready

#1360 Upgrade to postcss 8
  CHANGELOG.md
  package.json
  yarn.lock
Labels: breaking, dependencies

#1364 Release 2.0.0
  CHANGELOG.md
  package.json
Labels: release

#1366 Remove postcss-mixins, clean up configuration and dependency definition
  CHANGELOG.md
  package.json
  postcss.config.js
  yarn.lock
Labels: enhancement, ready

#1374 Release 2.1.0
  CHANGELOG.md
  package.json
Labels: release

#1375 Select: pass size property to react-select Select
  CHANGELOG.md
  src/components/select/Select.js
Labels: feature, ready

#1376 release/2.2.0
  CHANGELOG.md
  package.json
Labels: ready, release

#1378 Progresstracker followup
  CHANGELOG.md
  package.json
  src/components/progressTracker/progressTracker.stories.js
  src/components/progressTracker/theme.css
Labels: enhancement

#1382 Bump node version
  ci/deploy-storybook.yml
Labels: maintenance
