Repository teamleadercrm/ui, pull requests merged in 2020-11, with the labels that each got.

#1324 IconMenu: preserve visibility of the IconButton when menu is open
  src/components/menu/theme.css
Labels: enhancement, ready

#1325 Menu: fix border width rendering
  CHANGELOG.md
  src/components/menu/Menu.js
Labels: enhancement, ready

#1326 Release 1.0.9
  CHANGELOG.md
  package.json
Labels: ready, release

#1327 Menu: fix warning when outline width is undefined
  src/components/menu/Menu.js
Labels: bug, ready

#1328 IconMenu: fix menu positioning
  CHANGELOG.md
  src/components/menu/theme.css
Labels: bug, ready

#1329 Release 1.0.10
  CHANGELOG.md
  package.json
Labels: ready, release

#1330 Upgrade all babel dependencies
  package.json
  yarn.lock
Labels: dependencies, ready

#1335 [AHOY-424] DatePicker: improve display month picker content
  CHANGELOG.md
  src/components/datepicker/MonthPicker.js
  src/components/select/Select.js
  src/components/select/select.stories.js
Labels: enhancement, ready

#1339 Upgrade @teamleader/ui-icons & @teamleader/ui-typography
  package.json
  yarn.lock
Labels: dependencies, ready

#1338 [AHOY-423] Improve DatePicker header
  CHANGELOG.md
  src/components/datepicker/NavigationBar.js
  src/components/datepicker/theme.css
Labels: enhancement, ready

#1340 Release 1.0.11
  CHANGELOG.md
  package.json
Labels: ready, release

#1343 Upgrade all @storybook dependencies to the latest version
  package.json
  src/components/detailPage/detailPage.stories.js
  src/components/overviewPage/overviewPage.stories.js
  yarn.lock
Labels: maintenance, ready, storybook

#1346 Remove html-webpack-plugin dependency
  CHANGELOG.md
  package.json
  yarn.lock
Labels: dependencies
