Repository teamleadercrm/ui, pull requests merged in 2020-06, with the labels that each got.

#1144 Container: fixed & fluid padding should be consistent
  CHANGELOG.md
  src/components/container/theme.css
Labels: enhancement, ready

#1145 Release 0.44.1
  CHANGELOG.md
  package.json
Labels: ready, release

#1146 LabelValuePair: only add vertical padding when displaying label & value inline
  CHANGELOG.md
  src/components/labelValuePair/Label.js
  src/components/labelValuePair/LabelValuePair.js
  src/components/labelValuePair/Value.js
Labels: enhancement, ready

#1148 Tooltip: add `zIndex` prop and replace CSS rule
  CHANGELOG.md
  src/components/tooltip/Tooltip.js
  src/components/tooltip/theme.css
Labels: feature, ready

#1149 Release 0.44.2
  CHANGELOG.md
  package.json
Labels: ready, release

#1155 Tabs: remove inverted mode
  CHANGELOG.md
  src/components/tab/TabGroup.js
  src/components/tab/tab.stories.js
  src/components/tab/theme.css
Labels: breaking, maintenance, ready

#1156 DatePickerInput and DatePicker improvements and alignment fix
  CHANGELOG.md
  src/components/datepicker/DatePickerInput.js
  src/components/datepicker/MonthPicker.js
  src/components/datepicker/NavigationBar.js
  src/components/datepicker/datePicker.stories.js
  src/components/datepicker/theme.css
Labels: bug, enhancement, ready

#1162 release/0.45.0
  CHANGELOG.md
  package.json
Labels: release

#1160 Scrollable tabs
  CHANGELOG.md
  package.json
  src/components/tab/TabGroup.js
  src/components/tab/TitleTab.js
  src/components/tab/tab.stories.js
  src/components/tab/theme.css
  src/static/data/tab.js
  yarn.lock
Labels: feature, ready

#1161 💥 Remove IconTab component
  CHANGELOG.md
  index.d.ts
  src/components/tab/IconTab.js
  src/components/tab/index.js
  src/components/tab/tab.stories.js
  src/index.js
Labels: breaking, maintenance, ready

#1164 Release 0.46.0
  CHANGELOG.md
  package.json
Labels: breaking, ready, release

#1166 IconButton: add tint prop
  CHANGELOG.md
  src/components/iconButton/IconButton.js
  src/components/iconButton/iconButton.stories.js
Labels: enhancement, ready

#1168 release/0.46.1
  CHANGELOG.md
  package.json
Labels: release

#1169 Scrollable tabs: fine tune
  CHANGELOG.md
  src/components/tab/TabGroup.js
  src/components/tab/theme.css
Labels: enhancement, ready

#1170 IconButton: fix blurring `onMouseUp` and `onMouseLeave`
  CHANGELOG.md
  src/components/iconButton/IconButton.js
Labels: enhancement, ready

#1171 Button: fix blurring `onMouseUp` and `onMouseLeave`
  CHANGELOG.md
  src/components/button/Button.js
Labels: enhancement, ready

#1172 Release 0.46.2
  CHANGELOG.md
  package.json
Labels: ready, release

#1173 Menu: let the component grow inside of its container
  CHANGELOG.md
  src/components/menu/theme.css
Labels: bug, enhancement

#1175 Radio: fix inconsistent left margin in Firefox vs Chrome on Linux
  CHANGELOG.md
  src/components/radio/theme.css
Labels: bug, ready

#1180 Update all babel dependencies
  package.json
  yarn.lock
Labels: dependencies, ready

#1181 Allow passing style prop to ToastContainer
  CHANGELOG.md
  src/components/toast/ToastContainer.js
Labels: enhancement, ready

#1182 release/0.46.3
  CHANGELOG.md
  package.json
Labels: release

#1183 Box: forwardRef
  CHANGELOG.md
  index.d.ts
  src/components/badge/Badge.js
  src/components/box/Box.js
  src/components/button/Button.js
  src/components/iconButton/IconButton.js
  src/components/tab/TabGroup.js
  src/components/tab/TitleTab.js
  src/components/wysiwygEditor/LinkOptions.js
Labels: breaking, feature, ready

#1186 Release 0.47.0
  CHANGELOG.md
  package.json
Labels: breaking, ready, release

#1187 DatePicker - month selector: use 4 characters for french
  CHANGELOG.md
  src/components/datepicker/MonthPicker.js
  src/components/datepicker/datePicker.stories.js
Labels: enhancement, ready

#1193 DatePickerInput: footer
  CHANGELOG.md
  src/components/datepicker/DatePickerInput.js
  src/components/datepicker/datePicker.stories.js
Labels: feature, ready

#1195 DatePickerInput: remove bordered prop
  CHANGELOG.md
  src/components/datepicker/DatePickerInput.js
  src/components/datepicker/datePicker.stories.js
Labels: breaking, ready

#1194 Toggle: label max lines
  CHANGELOG.md
  src/components/toggle/Toggle.js
  src/components/toggle/theme.css
  src/components/toggle/toggle.stories.js
Labels: feature, ready

#1196 WysiwygEditor: Focus states
  CHANGELOG.md
  src/components/wysiwygEditor/InlineStylingOptions.js
  src/components/wysiwygEditor/LinkOptions.js
  src/components/wysiwygEditor/ListStylingOptions.js
  src/components/wysiwygEditor/WysiwygEditor.js
Labels: enhancement, ready

#1197 Release 0.48.0
  CHANGELOG.md
  package.json
Labels: breaking, ready, release

#1198 Fix Build Error
  src/components/wysiwygEditor/WysiwygEditor.js
Labels: bug, ready

#1199 Release 0.48.1
  CHANGELOG.md
  package.json
Labels: ready, release
