Repository teamleadercrm/ui, pull requests merged in 2020-04, with the labels that each got.

#977 Container component
  .storybook/preview.js
  CHANGELOG.md
  package.json
  postcss.config.js
  src/components/container/Container.js
  src/components/container/container.stories.js
  src/components/container/index.js
  src/components/container/theme.css
  src/index.js
Labels: new component, ready

#982 OverviewPage, OverviewPage.Header & OverviewPage.Body
  CHANGELOG.md
  src/components/overviewPage/OverviewPage.js
  src/components/overviewPage/OverviewPageBody.js
  src/components/overviewPage/OverviewPageHeader.js
  src/components/overviewPage/index.js
  src/components/overviewPage/overviewPage.stories.js
  src/index.js
Labels: new component, ready

#983 DetailPage, DetailPage.Header & DetailPage.Body
  CHANGELOG.md
  src/components/detailPage/DetailPage.js
  src/components/detailPage/DetailPageBody.js
  src/components/detailPage/DetailPageHeader.js
  src/components/detailPage/detailPage.stories.js
  src/components/detailPage/index.js
  src/components/detailPage/theme.css
  src/index.js
Labels: new component, ready

#990 Release 0.40.1
  CHANGELOG.md
  package.json
  src/components/widget/widget.stories.js
Labels: ready, release

#989 StatusLabel: use UIText components internally
  CHANGELOG.md
  src/components/statusLabel/StatusLabel.js
  src/components/statusLabel/theme.css
Labels: maintenance, ready

#991 Storybook: integrate Figma designs
  .storybook/main.js
  .storybook/preview.js
  package.json
  src/components/avatar/avatar.stories.js
  src/components/button/button.stories.js
  src/components/counter/counter.stories.js
  src/components/datagrid/datagrid.stories.js
  src/components/datepicker/datePicker.stories.js
  src/components/progressTracker/progressTracker.stories.js
  src/components/statusLabel/statusLabel.stories.js
  yarn.lock
Labels: feature, ready, storybook

#997 Marker component
  CHANGELOG.md
  src/components/typography/Marker.js
  src/components/typography/index.js
  src/components/typography/theme.css
  src/components/typography/typography.stories.js
  src/index.js
Labels: new component, ready

#996 EmptyState component
  CHANGELOG.md
  src/components/emptyState/EmptyState.js
  src/components/emptyState/emptyState.stories.js
  src/components/emptyState/index.js
  src/components/emptyState/theme.css
  src/components/widget/widget.stories.js
  src/index.js
Labels: new component, ready

#1000 Container: increase the width of the container
  CHANGELOG.md
  src/components/container/theme.css
Labels: enhancement, ready

#1003 DataGrid: decrease cell paddings with 6px
  CHANGELOG.md
  src/components/datagrid/BodyRow.js
  src/components/datagrid/HeaderRow.js
  src/components/datagrid/theme.css
Labels: enhancement, ready

#1004 Release 0.40.2
  CHANGELOG.md
  package.json
Labels: ready, release

#1006 Update some stories
  src/components/datagrid/datagrid.stories.js
  src/components/detailPage/detailPage.stories.js
  src/components/emptyState/emptyState.stories.js
  src/components/widget/widget.stories.js
Labels: maintenance, ready

#1005 Avatar: omit the team prop, otherwise it's spread onto the box
  CHANGELOG.md
  src/components/avatar/Avatar.js
Labels: bug

#1008 DetailPage.Header: fix adding a className
  CHANGELOG.md
  src/components/detailPage/DetailPageHeader.js
Labels: bug

#1007 Data grid: breaking changes
  CHANGELOG.md
  src/components/datagrid/BodyRow.js
  src/components/datagrid/Cell.js
  src/components/datagrid/DataGrid.js
  src/components/datagrid/FooterRow.js
  src/components/datagrid/HeaderCell.js
  src/components/datagrid/HeaderRow.js
  src/components/datagrid/datagrid.stories.js
  src/components/datagrid/theme.css
Labels: maintenance, ready

#1010 DetailPageHeader: add titleColor prop
  CHANGELOG.md
  src/components/detailPage/DetailPageHeader.js
  src/components/detailPage/detailPage.stories.js
Labels: feature, ready

#1011 Release 0.41.0
  CHANGELOG.md
  package.json
Labels: ready, release

#1009 IconButton: visual state updates
  CHANGELOG.md
  src/components/banner/Banner.js
  src/components/button/index.js
  src/components/button/theme.css
  src/components/datepicker/NavigationBar.js
  src/components/detailPage/detailPage.stories.js
  src/components/iconButton/IconButton.js
  src/components/iconButton/iconButton.stories.js
  src/components/iconButton/index.js
  src/components/iconButton/theme.css
  src/components/menu/IconMenu.js
  src/components/qTip/QTip.js
  src/components/tag/Tag.js
  src/components/toast/Toast.js
  src/index.js
Labels: maintenance, ready

#1014 Badge: visual state updates
  CHANGELOG.md
  src/components/badge/Badge.js
  src/components/badge/badge.stories.js
  src/components/badge/theme.css
Labels: maintenance, ready

#1021 WysiwygEditor: basic implementation
  package.json
  src/components/wysiwygEditor/WysiwygEditor.js
  src/components/wysiwygEditor/index.js
  src/components/wysiwygEditor/theme.css
  src/components/wysiwygEditor/wysiwygEditor.stories.js
  src/index.js
  yarn.lock
Labels: new component, ready

#1020 Tag: visual state updates
  CHANGELOG.md
  src/components/tag/Tag.js
  src/components/tag/tag.stories.js
  src/components/tag/theme.css
Labels: maintenance, ready

#1022 WysiwygEditor: List styling
  src/components/wysiwygEditor/WysiwygEditor.js
  src/components/wysiwygEditor/theme.css
Labels: new component, ready

#1027 Link (badged): visual state updates
  CHANGELOG.md
  src/components/link/Link.js
  src/components/link/link.stories.js
  src/components/link/theme.css
Labels: feature, maintenance, ready

#1028 Release 0.42.0
  CHANGELOG.md
  package.json
Labels: ready, release

#1036 DatePicker: fix broken import
  src/components/datepicker/DatePickerInputRange.js
  src/components/datepicker/utils.js
Labels: maintenance, ready

#1029 WysiwygEditor: add link functionality
  CHANGELOG.md
  src/components/wysiwygEditor/InlineStylingOptions.js
  src/components/wysiwygEditor/LinkOptions.js
  src/components/wysiwygEditor/ListStylingOptions.js
  src/components/wysiwygEditor/WysiwygEditor.js
  src/components/wysiwygEditor/decorators/index.js
  src/components/wysiwygEditor/decorators/linkDecorator.js
  src/components/wysiwygEditor/decorators/theme.css
  src/components/wysiwygEditor/theme.css
Labels: enhancement, ready

#1030 WysiwygEditor: Toolbar tooltips
  CHANGELOG.md
  src/components/tooltip/Tooltip.js
  src/components/wysiwygEditor/InlineStylingOptions.js
  src/components/wysiwygEditor/LinkOptions.js
  src/components/wysiwygEditor/ListStylingOptions.js
  src/utils/getOS.js
  src/utils/index.js
Labels: enhancement, hold, ready

#1037 WysiwygEditor: Add `locale` prop and translations
  CHANGELOG.md
  src/components/wysiwygEditor/InlineStylingOptions.js
  src/components/wysiwygEditor/LinkOptions.js
  src/components/wysiwygEditor/ListStylingOptions.js
  src/components/wysiwygEditor/WysiwygEditor.js
  src/components/wysiwygEditor/translations.js
Labels: enhancement, ready

#1039 Timer component
  CHANGELOG.md
  src/components/timer/Timer.js
  src/components/timer/index.js
  src/components/timer/theme.css
  src/components/timer/timer.stories.js
  src/index.js
Labels: new component, ready

#1038 WysiwygEditor: Link fixes
  CHANGELOG.md
  src/components/wysiwygEditor/LinkOptions.js
  src/components/wysiwygEditor/decorators/linkDecorator.js
Labels: bug, ready

#1043 Release 0.42.1
  CHANGELOG.md
  package.json
Labels: ready, release

#1044 WysiwygEditor: styling fixes
  CHANGELOG.md
  src/components/wysiwygEditor/WysiwygEditor.js
  src/components/wysiwygEditor/theme.css
Labels: bug, ready

#1045 Release 0.42.2
  CHANGELOG.md
  package.json
Labels: ready, release

#1046 Tag: re-add onClick and build with Badge components
  CHANGELOG.md
  src/components/badge/Badge.js
  src/components/tag/Tag.js
  src/components/tag/tag.stories.js
  src/components/tag/theme.css
Labels: bug, ready

#1047 Release 0.42.3
  CHANGELOG.md
  package.json
Labels: ready, release

#1050 Release 0.42.4
  CHANGELOG.md
  index.d.ts
  package.json
Labels: ready, release

#1052 WysiwygEditor: fallback to English when locale prop is non-supported locale
  CHANGELOG.md
  src/components/wysiwygEditor/WysiwygEditor.js
Labels: bug, ready

#1053 Release 0.42.5
  CHANGELOG.md
  package.json
Labels: ready, release

#1055 WysiwygEditor: Fix placeholder positioning
  CHANGELOG.md
  src/components/wysiwygEditor/theme.css
Labels: bug, ready

#1056 Release 0.42.6
  CHANGELOG.md
  package.json
Labels: ready, release

#1057 Fix linkDecorator href of WysiwygEditor
  CHANGELOG.md
  src/components/wysiwygEditor/decorators/linkDecorator.js
Labels: bug, ready

#1058 Release 0.42.7
  CHANGELOG.md
  package.json
Labels: ready, release

#1059 Button: handle overflowing text
  CHANGELOG.md
  src/components/button/Button.js
  src/components/button/button.stories.js
  src/components/button/theme.css
Labels: enhancement, ready

#1060 DataGrid: inverse sorting arrow direction
  CHANGELOG.md
  src/components/datagrid/HeaderCell.js
  src/components/datagrid/theme.css
Labels: enhancement, ready

#1063 Fix console warnings
  CHANGELOG.md
  src/components/emptyState/EmptyState.js
  src/components/typography/Marker.js
  src/components/typography/Text.js
Labels: maintenance, ready

#1065 Add caret in front of dependency versions
  package.json
  yarn.lock
Labels: maintenance, ready

#1064 Release 0.42.8
  CHANGELOG.md
  package.json
Labels: ready, release

#1071 SplitButton: prevent scroll lock (Popover)
  CHANGELOG.md
  src/components/button/index.js
  src/components/splitButton/SplitButton.js
  src/components/splitButton/index.js
  src/components/splitButton/splitButton.stories.js
  src/index.js
Labels: enhancement, ready

#1072 Button: icon + label spacing
  CHANGELOG.md
  src/components/button/Button.js
  src/components/button/theme.css
Labels: maintenance, ready

#1073 ButtonGroup: move to its own folder
  src/components/button/index.js
  src/components/button/theme.css
  src/components/buttonGroup/ButtonGroup.js
  src/components/buttonGroup/buttonGroup.stories.js
  src/components/buttonGroup/index.js
  src/components/buttonGroup/theme.css
  src/components/detailPage/detailPage.stories.js
  src/components/message/Message.js
  src/components/overviewPage/overviewPage.stories.js
  src/components/splitButton/SplitButton.js
  src/index.js
Labels: maintenance, ready

#1067 Fix incorrect month being displayed on initial render
  CHANGELOG.md
  src/components/datepicker/DatePicker.js
Labels: bug, ready
