Repository teamleadercrm/ui, pull requests merged in 2020-02, with the labels that each got.

#845 Select: override the default menu width
  CHANGELOG.md
  src/components/select/Select.js
  src/components/select/select.stories.js
Labels: enhancement, feature, ready

#846 NumericInput: fix min and max value
  CHANGELOG.md
  src/components/input/NumericInput.js
  src/components/input/input.stories.js
  src/components/input/utils.js
Labels: bug, ready

#847 Release 0.36.0
  CHANGELOG.md
  package.json
Labels: ready, release

#851 NumericInput: remove value parsing on change
  CHANGELOG.md
  src/components/input/NumericInput.js
Labels: bug, ready

#855 Release 0.36.1
  CHANGELOG.md
  package.json
Labels: ready, release

#841 DatePicker: MonthPicker with single select field
  CHANGELOG.md
  src/components/datepicker/DatePicker.js
  src/components/datepicker/DatePickerInput.js
  src/components/datepicker/MonthPicker.js
  src/components/datepicker/NavigationBar.js
  src/components/datepicker/datePicker.stories.js
  src/components/datepicker/theme.css
  src/components/input/SingleLineInputBase.js
  src/components/input/theme.css
Labels: feature, ready

#856 Release/0.36.2
  CHANGELOG.md
  package.json
Labels: ready, release

#868 DatePicker: MonthPicker fixes
  CHANGELOG.md
  src/components/datepicker/MonthPicker.js
Labels: enhancement, ready

#870 Release/0.36.3
  CHANGELOG.md
  package.json
Labels: ready, release

#872 [BUG] DatePickerInput: don't allow null to be returned as value
  src/components/datepicker/DatePickerInput.js
Labels: bug

#875 Dialog: expose a Header, Body and Footer component
  CHANGELOG.md
  src/components/dialog/Body.js
  src/components/dialog/Dialog.js
  src/components/dialog/DialogBase.js
  src/components/dialog/Footer.js
  src/components/dialog/Header.js
Labels: enhancement, ready

#876 NumericInput: remove value parsing in getDerivedStateFromProps
  CHANGELOG.md
  src/components/input/NumericInput.js
Labels: bug, ready

#877 Release 0.36.4
  CHANGELOG.md
  package.json
Labels: ready, release

#878 Menu: make sure menu items can shrink when needed
  src/components/menu/MenuItem.js
  src/components/menu/theme.css
Labels: enhancement, ready

#879 NumericInput: text align right
  CHANGELOG.md
  src/components/input/InputBase.js
  src/components/input/input.stories.js
  src/components/input/theme.css
Labels: feature, ready

#881 [AHOY-360] Remove icon from validation messages
  CHANGELOG.md
  src/components/validationText/ErrorText.js
  src/components/validationText/HelpText.js
  src/components/validationText/SuccessText.js
  src/components/validationText/WarningText.js
Labels: enhancement, ready

#882 Release 0.36.5
  CHANGELOG.md
  package.json
Labels: ready, release

#883 ✨ SplitButton: add disabled state
  CHANGELOG.md
  src/components/button/SplitButton.js
  src/components/button/splitButton.stories.js
Labels: ready

#884 Storybook: upgrade to 5.3.14
  .storybook/addons.js
  .storybook/main.js
  .storybook/manager.js
  .storybook/preview.js
  .storybook/styles.js
  .storybook/teamleaderTheme.js
  package.json
  yarn.lock
Labels: dependencies, maintenance, ready, storybook

#889 Release 0.36.6
  CHANGELOG.md
  package.json
Labels: release

#895 Avatar stack: fix margins
  CHANGELOG.md
  src/components/avatar/AvatarStack.js
  src/components/avatar/theme.css
Labels: enhancement, ready
