Repository teamleadercrm/ui, pull requests merged in 2021-02, with the labels that each got.

#1465 MenuItem: accept children
  CHANGELOG.md
  src/components/menu/MenuItem.js
  src/components/menu/menu.stories.js
Labels: feature, ready

#1466 Release 2.4.0
  CHANGELOG.md
  package.json
Labels: ready, release

#1474 Select: fix menu portal target logic
  CHANGELOG.md
  src/components/select/Select.js
Labels: bug, ready

#1480 Release 2.4.1
  CHANGELOG.md
  package.json
Labels: ready, release

#1482 Select: set menuShouldBlockScroll as the default value
  CHANGELOG.md
  src/components/select/Select.js
Labels: breaking, bug, ready

#1483 Release 3.0.0
  CHANGELOG.md
  package.json
Labels: breaking, ready, release

#1485 Select: set menuPlacement 'auto' as the default value
  CHANGELOG.md
  src/components/select/Select.js
Labels: enhancement, ready

#1486 Release 3.1.0
  CHANGELOG.md
  package.json
Labels: ready, release

#1490 eslint-config-standard-jsx should be a dev dependency
  package.json
Labels: bug

#1498 StatusLabel: add text overflow mode
  CHANGELOG.md
  src/components/statusLabel/StatusLabel.js
  src/components/statusLabel/theme.css
Labels: feature, ready

#1505 Release 3.2.0
  CHANGELOG.md
  package.json
Labels: ready, release

#1502 Tag v2
  CHANGELOG.md
  src/components/tag/Tag.js
  src/components/tag/tag.stories.js
  src/components/tag/theme.css
Labels: maintenance, ready
