Repository teamleadercrm/ui, pull requests merged in 2021-12, with the labels that each got.

#1876 Update wysiwyg link popup z-index
  CHANGELOG.md
  src/components/wysiwygEditor/LinkOptions.js
Labels: bug, ready

#1878 Release/10.1.2
  CHANGELOG.md
  package.json
Labels: ready, release

#1877 `Widget`, `IslandGroup`: ref forwarding, `boxProps`: style property
  CHANGELOG.md
  src/components/box/boxProps.js
  src/components/datepicker/DatePicker.js
  src/components/datepicker/DatePickerRange.js
  src/components/island/Island.js
  src/components/island/IslandGroup.js
  src/components/menu/MenuItem.js
  src/components/widget/Body.js
  src/components/widget/Widget.js
Labels: ready

#1881 [11.0.0] - 2021-12-20
  CHANGELOG.md
  package.json
Labels: ready, release

#1882 Remove custom storybook styling, fix theme & initial load
  .storybook/manager-head.html
  .storybook/manager.js
  .storybook/preview-head.html
  .storybook/preview.js
  .storybook/stories/about/about.stories.mdx
  .storybook/theme.js
Labels: ready, storybook
