Repository teamleadercrm/ui, pull requests merged in 2021-01, with the labels that each got.

#1416 Fix Dialog horizontal positioning
  CHANGELOG.md
  src/components/dialog/theme.css
Labels: bug, ready

#1420 Release 2.2.1
  CHANGELOG.md
  package.json
Labels: ready, release

#1424 Revert "⬆️ Bump react-select from 3.0.4 to 3.1.1"
  package.json
  yarn.lock
Labels: bug, dependencies, ready

#1425 Release 2.2.2
  CHANGELOG.md
  package.json
Labels: ready, release

#1436 Counter: fix centering when zooming out
  CHANGELOG.md
  src/components/counter/theme.css
Labels: bug, ready

#1439 Release 2.3.0
  CHANGELOG.md
  package.json
Labels: ready, release

#1446 Storybook: add colors page
  .storybook/stories/colors/colors.stories.mdx
Labels: ready, storybook

#1450 Add about page
  .storybook/stories/about/about.stories.mdx
Labels: ready, storybook

#1451 Add depths page
  .storybook/stories/depths/assets/depths.svg
  .storybook/stories/depths/depths.stories.mdx
Labels: ready, storybook

#1452 Add icons page
  .storybook/stories/depths/depths.stories.mdx
  .storybook/stories/icons/assets/bounding_1.svg
  .storybook/stories/icons/assets/bounding_2.svg
  .storybook/stories/icons/assets/bounding_3.svg
  .storybook/stories/icons/assets/bounding_4.svg
  .storybook/stories/icons/assets/placement.svg
  .storybook/stories/icons/assets/secondary_metaphors.svg
  .storybook/stories/icons/icons.stories.mdx
Labels: ready, storybook

#1453 Update to latest Storybook dependencies
  package.json
  yarn.lock
Labels: dependencies, ready

#1454 Set Docs as the default view mode
  .storybook/preview.js
Labels: ready, storybook
