Repository teamleadercrm/ui, pull requests merged in 2021-07, with the labels that each got.

#1717 [CORE-4804] Filter selection component
  src/components/filterSelection/FilterSelection.js
  src/components/filterSelection/filterSelection.stories.js
  src/components/filterSelection/index.js
  src/components/filterSelection/theme.css
  src/index.js
Labels: feature, new component, ready

#1720 release/6.6.0
  CHANGELOG.md
  package.json
Labels: release

#1721 Fix update filter selection
  CHANGELOG.md
  src/components/filterSelection/FilterSelection.js
  src/components/filterSelection/theme.css
  src/constants/keys.js
Labels: enhancement, new component, ready

#1722 [FIX] height and hover state of FilterSelection
  CHANGELOG.md
  src/components/filterSelection/FilterSelection.js
  src/components/filterSelection/theme.css
Labels: bug, ready

#1727 Add forward references to Button and Input components, fix display name on existing forwardRefs
  .eslintrc
  CHANGELOG.md
  src/components/box/Box.js
  src/components/button/Button.js
  src/components/datagrid/BodyRow.js
  src/components/datagrid/FooterRow.js
  src/components/datagrid/HeaderRow.js
  src/components/datagrid/Row.js
  src/components/dialog/Body.js
  src/components/filterSelection/FilterSelection.js
  src/components/hoc/DocumentObjectProvider/DocumentObjectProvider.js
  src/components/input/DurationInput.js
  src/components/input/Input.js
  src/components/input/InputBase.js
  src/components/input/NumericInput.js
  src/components/input/SingleLineInputBase.js
  src/components/input/Textarea.js
  src/components/input/TimeInput.js
  src/components/marketingTab/MarketingTab.js
  src/components/select/Select.js
  src/components/tab/TitleTab.js
Labels: ready

#1729 `Overlay`: make aria compliant, `QTip`: remove component
  .storybook/stories/playground/zIndexes.stories.js
  CHANGELOG.md
  index.d.ts
  src/components/datepicker/localeUtils.js
  src/components/dialog/DialogBase.js
  src/components/dialog/theme.css
  src/components/iconButton/IconButton.js
  src/components/overlay/Overlay.js
  src/components/overlay/theme.css
  src/components/popover/Popover.js
  src/components/qTip/QTip.js
  src/components/qTip/index.js
  src/components/qTip/qTip.stories.js
  src/components/qTip/theme.css
  src/index.js
Labels: ready

#1731 `Dialog` and `Popover`: make aria compliant
  CHANGELOG.md
  src/components/datepicker/DatePickerInput.js
  src/components/dialog/Body.js
  src/components/dialog/Dialog.js
  src/components/dialog/DialogBase.js
  src/components/dialog/dialog.stories.js
  src/components/dialog/dialogBase.stories.js
  src/components/popover/Popover.js
  src/utils/useFocusTrap/index.js
  src/utils/useFocusTrap/useFocusTrap.js
  src/utils/useFocusTrap/utils.js
Labels: ready

#1736 Align ref forwarding for remaining components
  .storybook/stories/playground/forms.stories.js
  CHANGELOG.md
  src/components/iconButton/IconButton.js
  src/components/iconButton/iconButton.stories.js
  src/components/link/Link.js
  src/components/marketingButton/MarketingButton.js
  src/components/marketingLink/MarketingLink.js
  src/components/marketingTab/MarketingTab.js
  src/components/tab/TitleTab.js
Labels: ready

#1735 Release/7.0.0
  CHANGELOG.md
  package.json
Labels: release

#1737 Fix regression bugs caused by ref forwarding and aria-compliancy
  CHANGELOG.md
  src/components/input/NumericInput.js
  src/components/overlay/Overlay.js
  src/components/popover/Popover.js
  src/components/select/Select.js
  src/constants/keys.js
Labels: bug, ready

#1738 Don't allow more characters than needed in duration input
  CHANGELOG.md
  src/components/input/DurationInput.js
Labels: hold

#1739 release/8.0.0
  CHANGELOG.md
  package.json
Labels: ready, release

#1741 [FIX] Text color when hovering/ background color of clear button when focused
  CHANGELOG.md
  package.json
  src/components/filterSelection/filterSelection.stories.js
  src/components/filterSelection/theme.css
Labels: bug, ready

#1743 `AsyncSelect`: also pass the inputActionMeta to the onInputChange handler
  CHANGELOG.md
  src/components/select/AsyncSelect.js
Labels: bug

#1744 Release/8.0.1
  CHANGELOG.md
Labels: ready, release

#1745 [IN-3873] add 'powered by' button
  .storybook/webpack.config.js
  CHANGELOG.md
  package.json
  src/components/poweredByButton/PoweredByButton.js
  src/components/poweredByButton/index.js
  src/components/poweredByButton/poweredButton.stories.js
  src/components/poweredByButton/teamleaderLogo.svg
  src/components/poweredByButton/teamleaderLogoBig.svg
  src/components/poweredByButton/teamleaderText.svg
  src/components/poweredByButton/theme.css
  yarn.lock
Labels: ready
