Repository teamleadercrm/ui, pull requests merged in 2021-05, with the labels that each got.

#1634 Release 5.0.0
  CHANGELOG.md
  package.json
Labels: breaking, ready, release

#1641 [In-3666] more accessible progress tracker
  CHANGELOG.md
  src/components/progressTracker/ProgressStep.js
  src/components/progressTracker/ProgressTracker.js
  src/components/progressTracker/progressTracker.stories.js
  src/components/progressTracker/theme.css
Labels: breaking, ready

#1643 [AHOY-437] Pagination: remove previous & next button labels
  CHANGELOG.md
  src/components/pagination/Pagination.js
  src/components/pagination/pagination.stories.js
Labels: breaking, ready

#1646 Introduce `DurationInput` & improvements to the `NumericInput`
  CHANGELOG.md
  src/components/input/DurationInput.js
  src/components/input/NumericInput.js
  src/components/input/index.js
  src/components/input/input.stories.js
  src/index.js
Labels: new component

#1647 `DurationInput`: Follow up
  CHANGELOG.md
  src/components/input/DurationInput.js
  src/components/input/theme.css
Labels: enhancement, ready

#1648 Release 6.0.0
  CHANGELOG.md
  package.json
Labels: breaking, ready, release

#1650 `DurationInput`: add `textAlignRight` property
  CHANGELOG.md
  src/components/input/DurationInput.js
Labels: enhancement, ready

#1651 🔖 release/6.1.0
  CHANGELOG.md
  package.json
Labels: release

#1652 `DurationInput`: Consistent empty values
  CHANGELOG.md
  src/components/input/DurationInput.js
Labels: bug, ready
