Repository teamleadercrm/ui, pull requests merged in 2021-09, with the labels that each got.

#1784 Progress tracker spacing
  CHANGELOG.md
  src/components/progressTracker/ProgressStep.js
  src/components/progressTracker/progressTracker.stories.js
  src/components/progressTracker/theme.css
Labels: ready

#1789 Fix types for components with static properties
  CHANGELOG.md
  index.d.ts
Labels: ready

#1790 Release 8.2.0
  CHANGELOG.md
  package.json
Labels: ready, release

#1794 `DurationInput`: add `small`, `medium` (default) and `large` size property
  CHANGELOG.md
  src/components/input/DurationInput.js
Labels: feature

#1791 Fix date picker locale
  CHANGELOG.md
  src/components/datepicker/DatePicker.js
  src/components/datepicker/DatePickerInput.js
  src/components/datepicker/DatePickerRange.js
  src/components/datepicker/datePicker.stories.js
Labels: ready

#1798 release/8.3.0
  CHANGELOG.md
  package.json
Labels: ready, release
