Repository teamleadercrm/ui, pull requests merged in 2021-03, with the labels that each got.

#1510 Marketing button
  .storybook/utils/index.js
  CHANGELOG.md
  src/components/marketingButton/MarketingButton.js
  src/components/marketingButton/index.js
  src/components/marketingButton/marketingButton.stories.js
  src/components/marketingButton/theme.css
  src/index.js
Labels: new component, ready

#1515 MarketingMarker
  CHANGELOG.md
  src/components/marketingMarker/MarketingMarker.js
  src/components/marketingMarker/index.js
  src/components/marketingMarker/marketingMarker.stories.js
  src/components/marketingMarker/theme.css
  src/index.js
Labels: new component, ready

#1522 MarketingLink
  CHANGELOG.md
  src/components/marketingLink/MarketingLink.js
  src/components/marketingLink/index.js
  src/components/marketingLink/marketingLink.stories.js
  src/components/marketingLink/theme.css
  src/index.js
Labels: new component, ready

#1527 Release 4.0.0
  CHANGELOG.md
  package.json
Labels: ready, release

#1537 Update @teamleader/ui-typography and font family variables
  CHANGELOG.md
  package.json
  src/components/avatar/theme.css
  src/components/counter/theme.css
  src/components/datagrid/theme.css
  src/components/datepicker/theme.css
  src/components/input/theme.css
  src/components/link/theme.css
  src/components/marketingTypography/theme.css
  src/components/pagination/theme.css
  src/components/progressTracker/theme.css
  src/components/select/Select.js
  src/components/select/theme.css
  src/components/toast/theme.css
  src/components/wysiwygEditor/WysiwygEditor.js
  src/components/wysiwygEditor/theme.css
  yarn.lock
Labels: maintenance, ready

#1541 MarketingLockBadge component
  CHANGELOG.md
  src/components/marketingLockBadge/MarketingLockBadge.js
  src/components/marketingLockBadge/index.js
  src/components/marketingLockBadge/marketingLockBadge.stories.js
  src/components/marketingLockBadge/theme.css
  src/index.js
Labels: new component, ready

#1548 Revert "Bump postcss-each from 0.10.0 to 1.0.0"
  package.json
  yarn.lock
Labels: breaking, ready

#1550 MarketingStatusLabel
  CHANGELOG.md
  package.json
  src/components/marketingStatusLabel/MarketingStatusLabel.js
  src/components/marketingStatusLabel/index.js
  src/components/marketingStatusLabel/marketingStatusLabel.stories.js
  src/components/marketingStatusLabel/theme.css
  src/index.js
  yarn.lock
Labels: new component, ready

#1551 MarketingTab
  CHANGELOG.md
  src/components/marketingTab/MarketingTab.js
  src/components/marketingTab/index.js
  src/components/marketingTab/marketingTab.stories.js
  src/components/marketingTab/theme.css
  src/index.js
Labels: new component, ready

#1552 MarketingHeading2
  CHANGELOG.md
  src/components/marketingTypography/MarketingHeading2.js
  src/components/marketingTypography/index.js
  src/components/marketingTypography/marketingTypography.stories.js
  src/components/marketingTypography/theme.css
  src/index.js
Labels: new component, ready

#1553 Fix story path config
  .storybook/main.js
Labels: maintenance, ready, storybook

#1557 Release 4.1.0
  CHANGELOG.md
  package.json
Labels: ready, release

#1560 Upgrade @teamleader/ui-typography to the latest version (2.0.1)
  package.json
  yarn.lock
Labels: enhancement, ready

#1561 Release 4.2.0
  CHANGELOG.md
  package.json
Labels: ready, release

#1566 Remove dependency on `@sambego/storybook-state`
  .storybook/stories/playground/dialogs.stories.js
  .storybook/stories/playground/zIndexes.stories.js
  CHANGELOG.md
  package.json
  src/components/buttonGroup/buttonGroup.stories.js
  src/components/dialog/dialog.stories.js
  src/components/input/input.stories.js
  src/components/passport/passport.stories.js
  src/components/popover/popover.stories.js
  src/components/qTip/qTip.stories.js
  src/components/radio/radio.stories.js
  src/components/toast/toast.stories.js
  yarn.lock
Labels: dependencies, ready, storybook

#1570 Update reviewers to fix dependabot assignments
  .github/dependabot.yml
Labels: maintenance, ready

#1584 SplitButton: fix text overflow ellipsis
  src/components/buttonGroup/theme.css
Labels: enhancement, ready
