Repository teamleadercrm/ui, pull requests merged in 2021-04, with the labels that each got.

#1586 Select: tiny-sized variant
  CHANGELOG.md
  src/components/select/Select.js
  src/components/select/select.stories.js
  src/components/select/theme.css
Labels: feature, ready

#1587 SplitButton: update story
  src/components/splitButton/splitButton.stories.js
Labels: maintenance, ready

#1588 Dialog & DialogBase: split off stories and eliminate Knobs
  src/components/dialog/dialog.stories.js
  src/components/dialog/dialogBase.stories.js
Labels: maintenance, ready

#1589 Release 4.3.0
  CHANGELOG.md
  package.json
Labels: ready, release

#1591 Input: add tiny size variant
  CHANGELOG.md
  src/components/input/InputBase.js
  src/components/input/input.stories.js
  src/components/input/theme.css
Labels: feature, ready

#1592 Select: fix input and placeholder spacing
  CHANGELOG.md
  src/components/select/Select.js
Labels: bug, ready

#1593 release/4.4.0
  CHANGELOG.md
  package.json
Labels: ready, release

#1595 Timer: update according to the latest design specs
  CHANGELOG.md
  src/components/timer/Timer.js
  src/components/timer/theme.css
Labels: maintenance, ready

#1596 Release 4.5.0
  CHANGELOG.md
  package.json
Labels: ready, release

#1599 Timer: change display inline-flex to flex
  src/components/timer/Timer.js
Labels: enhancement, ready

#1600 Release 4.5.1
  CHANGELOG.md
  package.json
Labels: ready, release

#1606 release/4.6.0
  CHANGELOG.md
  package.json
Labels: ready, release

#1609 Upgrade Storybook to the latest version (6.2.8)
  package.json
  yarn.lock
Labels: maintenance, ready, storybook

#1610 Upgrade all babel dependencies
  package.json
  yarn.lock
Labels: dependencies, maintenance, ready

#1612 Replace Message by SilentBanner
  CHANGELOG.md
  index.d.ts
  src/components/compactMessage/CompactMessage.js
  src/components/compactMessage/index.js
  src/components/compactMessage/theme.css
  src/components/message/Message.js
  src/components/message/message.stories.js
  src/components/message/theme.css
  src/components/silentBanner/SilentBanner.js
  src/components/silentBanner/index.js
  src/components/silentBanner/silentBanner.stories.js
  src/index.js
Labels: breaking, maintenance, ready

#1617 Input: remove width 100% from the `.wrapper`.
  CHANGELOG.md
  src/components/input/theme.css
Labels: bug, ready
