Repository teamleadercrm/ui, pull requests merged in 2021-06, with the labels that each got.

#1662 Update ui-typography to 2.0.2
  CHANGELOG.md
  package.json
  yarn.lock
Labels: ready

#1659 FIX: Make stepper events trigger the onChange event
  CHANGELOG.md
  src/components/input/InputBase.js
  src/components/input/NumericInput.js
  src/components/input/SingleLineInputBase.js
Labels: enhancement, hold, ready

#1668 Release 6.2.0
  CHANGELOG.md
  package.json
Labels: ready, release

#1672 Fix Toggle layout
  CHANGELOG.md
  src/components/toggle/Toggle.js
  src/components/toggle/theme.css
  src/components/toggle/toggle.stories.js
Labels: bug, ready

#1687 DurationInput: updated design and interaction
  CHANGELOG.md
  src/components/input/DurationInput.js
  src/components/input/NumericInput.js
  src/components/input/theme.css
  src/constants/index.js
  src/constants/keys.js
Labels: enhancement, ready

#1688 Release/6.3.0
  CHANGELOG.md
  package.json
Labels: ready

#1694 NumericInput - increasing or decreasing the stepper should be rounded to the step
  CHANGELOG.md
  src/components/input/NumericInput.js
Labels: bug, ready

#1689 Add `max` and `error` props to `DurationInput`
  CHANGELOG.md
  src/components/input/DurationInput.js
  src/components/input/theme.css
Labels: enhancement, ready

#1690 Clean up build process
  .babelrc
  .storybook/main.js
  .storybook/webpack.config.js
  package.json
  yarn.lock
Labels: ready, storybook

#1695 release/6.4.0
  CHANGELOG.md
  package.json
Labels: ready, release

#1698 `DurationInput`: accept `id` property
  CHANGELOG.md
  src/components/input/DurationInput.js
Labels: ready

#1700 release/6.5.0
  CHANGELOG.md
  package.json
Labels: ready, release

#1704 Fix duration input overlapping other elements
  CHANGELOG.md
  src/components/input/theme.css
Labels: bug, ready

#1709 release/6.5.1
  CHANGELOG.md
  package.json
Labels: release

#1710 Check every direction when rendering the popup for the best fit with a preference for the opposite
  CHANGELOG.md
  src/components/popover/Popover.js
  src/components/popover/positionCalculation.js
Labels: bug
