Repository teamleadercrm/ui, pull requests merged in 2022-02, with the labels that each got.

#1958 [LIG-835] Prevent clicks in underlying `Dialog` from closing parent `Overlay`
  CHANGELOG.md
  src/components/overlay/Overlay.js
Labels: bug, ready

#1962 Release/12.1.1
  CHANGELOG.md
  package.json
Labels: ready, release

#1971 Investigate dialog on esc key down not triggering
  CHANGELOG.md
  src/components/dialog/dialog.stories.js
  src/utils/useFocusTrap/useFocusTrap.js
Labels: bug

#1993 Visual improvement of dialog and select components in UI library
  CHANGELOG.md
  src/components/dialog/Dialog.js
  src/components/dialog/Footer.js
  src/components/select/select.stories.js
Labels: ready

#2002 Add email selector component
  CHANGELOG.md
  index.d.ts
  src/components/emailSelector/Autocomplete.js
  src/components/emailSelector/EmailSelector.js
  src/components/emailSelector/EmailSuggestion.js
  src/components/emailSelector/Label.js
  src/components/emailSelector/emailSelector.stories.js
  src/components/emailSelector/emailSelector.stories.spec.js
  src/components/emailSelector/index.js
  src/components/emailSelector/theme.css
  src/components/emailSelector/utils.js
  src/index.js
Labels: ready, feature

#2003 Marketing button group
  CHANGELOG.md
  index.d.ts
  src/components/marketingButtonGroup/Button.js
  src/components/marketingButtonGroup/MarketingButtonGroup.js
  src/components/marketingButtonGroup/index.js
  src/components/marketingButtonGroup/marketingButtonGroup.stories.js
  src/components/marketingButtonGroup/theme.css
  src/index.js
Labels: ready, new component

#2007 Release/12.2.0
  CHANGELOG.md
  package.json
Labels: ready, release

#2009 Updated type index to include MarketingButtonGroup.Button
  CHANGELOG.md
  index.d.ts
Labels: bug, enhancement, ready

#2010 Release/12.2.1
  CHANGELOG.md
  package.json
Labels: release

#2012 Update dependabot reviewers
  .github/dependabot.yml
Labels: ready

#2008 [ENHANCEMENT] Select: change spacing between input and dropdown
  CHANGELOG.md
  src/components/popover/positionCalculation.js
  src/components/select/Select.js
Labels: ready

#2014 [FIX] Flex basis for correct width on SingleLineInputBase
  CHANGELOG.md
  src/components/input/SingleLineInputBase.js
Labels: ready

#2015 Release 12.3.0
  CHANGELOG.md
  package.json
Labels: ready, release

#2016 Remove empty sections
  CHANGELOG.md
Labels: ready
