Repository teamleadercrm/ui, pull requests merged in 2022-08, with the labels that each got.

#2314 [FRAF-873] - Pass onClick to the wrapper of checkbox
  CHANGELOG.md
  src/components/checkbox/Checkbox.tsx
Labels: bug

#2315 Release/16.0.1
  CHANGELOG.md
  package.json
Labels: release

#2321 [GUILD] Typescript `ValidationText`
  src/components/validationText/ErrorText.js
  src/components/validationText/ErrorText.tsx
  src/components/validationText/HelpText.js
  src/components/validationText/HelpText.tsx
  src/components/validationText/SuccessText.js
  src/components/validationText/SuccessText.tsx
  src/components/validationText/ValidationText.js
  src/components/validationText/ValidationText.tsx
  src/components/validationText/WarningText.js
  src/components/validationText/WarningText.tsx
  src/components/validationText/index.js
  src/components/validationText/index.tsx
  src/components/validationText/validationText.stories.tsx
  src/index.ts
Labels: ready, maintenance

#2319 [GUILD] Typescript `Typography`
  src/components/button/Button.tsx
  src/components/detailPage/DetailPageHeader.tsx
  src/components/emptyState/EmptyState.tsx
  src/components/typography/Marker.js
  src/components/typography/Marker.tsx
  src/components/typography/Monospaced.js
  src/components/typography/Monospaced.tsx
  src/components/typography/Text.js
  src/components/typography/Text.tsx
  src/components/typography/index.ts
  src/components/typography/typography.stories.tsx
  src/components/validationText/ErrorText.tsx
  src/components/validationText/HelpText.tsx
  src/components/validationText/SuccessText.tsx
  src/components/validationText/WarningText.tsx
  src/index.ts
Labels: ready, maintenance

#2322 [GUILD] - Convert `Overlay` to TS
  src/components/overlay/Overlay.js
  src/components/overlay/Overlay.tsx
  src/components/overlay/index.js
  src/components/overlay/index.ts
  src/index.ts
Labels: ready, maintenance

#2253 [GUILD] Convert ahoy `ProgressTracker` to typescript
  src/components/progressTracker/ProgressStep.js
  src/components/progressTracker/ProgressStep.tsx
  src/components/progressTracker/ProgressTracker.js
  src/components/progressTracker/ProgressTracker.tsx
  src/components/progressTracker/index.js
  src/components/progressTracker/index.ts
  src/components/progressTracker/progressTracker.stories.tsx
  src/index.ts
Labels: ready, maintenance

#2323 [GUILD] - Convert `Radio` to TS
  src/components/radio/RadioButton.js
  src/components/radio/RadioButton.tsx
  src/components/radio/RadioGroup.js
  src/components/radio/RadioGroup.tsx
  src/components/radio/index.js
  src/components/radio/index.ts
  src/components/radio/radio.stories.tsx
  src/index.ts
Labels: ready, maintenance

#2326 [GUILD] - Convert `Widget` to TS
  src/components/widget/Body.js
  src/components/widget/Body.tsx
  src/components/widget/Footer.js
  src/components/widget/Footer.tsx
  src/components/widget/Header.js
  src/components/widget/Header.tsx
  src/components/widget/Widget.js
  src/components/widget/Widget.tsx
  src/components/widget/index.ts
  src/components/widget/widget.stories.tsx
Labels: ready, maintenance

#2327 [GUILD] Upgrade Storybook - remove addon-knobs dep
  .storybook/main.js
  .storybook/stories/playground/zIndexes.stories.js
  package.json
  src/components/datepicker/datePicker.stories.tsx
  src/components/detailPage/detailPage.stories.tsx
  src/components/emailSelector/emailSelector.stories.tsx
  src/components/input/input.stories.tsx
  src/components/overviewPage/overviewPage.stories.tsx
  src/components/popover/popover.stories.tsx
  src/components/progressTracker/progressTracker.stories.tsx
  src/components/tab/tab.stories.tsx
  src/components/tooltip/tooltip.stories.js
  yarn.lock
Labels: ready, dependencies

#2328 Release/16.0.2
  CHANGELOG.md
  package.json
Labels: ready, release
