Repository teamleadercrm/ui, pull requests merged in 2022-05, with the labels that each got.

#2105 Add tooltips to Avatar and AvatarStack
  CHANGELOG.md
  src/components/avatar/Avatar.js
  src/components/avatar/AvatarStack.js
  src/components/avatar/AvatarStackOverflow.tsx
  src/components/avatar/avatarStack.stories.js
Labels: ready, feature

#2106 🔖 Bump version
  CHANGELOG.md
  package.json
Labels: release

#2108 Bump react-draft-wysiwyg to support react 17
  package.json
  yarn.lock
Labels: dependencies

#2110 Bump react-day-picker to the latest version on v7
  package.json
  yarn.lock
Labels: dependencies

#2118 [GUILD] support react 17
  CHANGELOG.md
  package.json
  yarn.lock
Labels: ready, dependencies

#2120 Release 14.5.0
  CHANGELOG.md
  package.json
Labels: release

#2126 [GUILD] Typescript Counter
  src/components/box/Box.tsx
  src/components/counter/Counter.tsx
  src/components/counter/counter.stories.spec.js
  src/components/counter/counter.stories.spec.tsx
  src/components/counter/counter.stories.tsx
Labels: ready, maintenance

#2117 [GUILD] Typescript bullet
  src/components/bullet/Bullet.js
  src/components/bullet/Bullet.tsx
  src/components/bullet/bullet.stories.spec.js
  src/components/bullet/bullet.stories.spec.tsx
  src/components/bullet/bullet.stories.tsx
  src/components/bullet/index.ts
Labels: ready, maintenance

#2122 [GUILD] Typescript ButtonGroup
  package.json
  src/@types/@teamleader/ui-icons.d.ts
  src/components/buttonGroup/ButtonGroup.js
  src/components/buttonGroup/ButtonGroup.tsx
  src/components/buttonGroup/buttonGroup.stories.spec.tsx
  src/components/buttonGroup/buttonGroup.stories.tsx
  src/components/buttonGroup/index.ts
  yarn.lock
Labels: ready, maintenance

#2115 [GUILD] Typescript utils
  src/utils/getOS.ts
  src/utils/index.ts
  src/utils/useFocusTrap/index.ts
  src/utils/useFocusTrap/useFocusTrap.tsx
  src/utils/useFocusTrap/utils.js
  src/utils/useFocusTrap/utils.ts
Labels: ready, maintenance

#2133 [14.5.1] - 2022-05-12
  CHANGELOG.md
  package.json
Labels: release

#2121 [GUILD] Typescript `Avatar` and `AvatarStack`
  src/components/avatar/Avatar.js
  src/components/avatar/Avatar.tsx
  src/components/avatar/AvatarAdd.js
  src/components/avatar/AvatarAdd.tsx
  src/components/avatar/AvatarAnonymous.js
  src/components/avatar/AvatarAnonymous.tsx
  src/components/avatar/AvatarImage.js
  src/components/avatar/AvatarImage.tsx
  src/components/avatar/AvatarInitials.js
  src/components/avatar/AvatarInitials.tsx
  src/components/avatar/AvatarOverlay.js
  src/components/avatar/AvatarOverlay.tsx
  src/components/avatar/AvatarStack.js
  src/components/avatar/AvatarStack.tsx
  src/components/avatar/AvatarStackOverflow.tsx
  src/components/avatar/AvatarTeam.js
  src/components/avatar/AvatarTeam.tsx
  src/components/avatar/avatar.stories.spec.tsx
  src/components/avatar/avatar.stories.tsx
  src/components/avatar/avatarStack.stories.spec.tsx
  src/components/avatar/avatarStack.stories.tsx
  src/components/avatar/index.ts
  src/components/avatar/types.ts
Labels: ready, maintenance

#2138 Fix icon menu
  CHANGELOG.md
  src/components/menu/Menu.js
  src/components/utils/events.js
Labels: bug, ready

#2139 [14.5.2] - 2022-05-13
  CHANGELOG.md
  package.json
Labels: ready, release

#2113 [GUILD] Typescript Badge
  CHANGELOG.md
  src/components/badge/Badge.js
  src/components/badge/Badge.tsx
  src/components/badge/badge.stories.tsx
  src/components/badge/index.ts
Labels: ready, maintenance

#2140 [GUILD] Typescript `LoadingBar` and `LoadingSpinner`
  src/components/loadingBar/LoadingBar.js
  src/components/loadingBar/LoadingBar.tsx
  src/components/loadingBar/index.ts
  src/components/loadingBar/loadingBar.stories.js
  src/components/loadingBar/loadingBar.stories.tsx
  src/components/loadingSpinner/LoadingSpinner.js
  src/components/loadingSpinner/LoadingSpinner.tsx
  src/components/loadingSpinner/index.ts
  src/components/loadingSpinner/loadingSpinner.stories.js
  src/components/loadingSpinner/loadingSpinner.stories.tsx
Labels: ready

#2150 Remove redundant babel dependencies
  package.json
  yarn.lock
Labels: ready, dependencies

#2155 Remove css minification in output bundle
  .storybook/webpack.config.js
  CHANGELOG.md
  package.json
  postcss.config.js
  yarn.lock
Labels: ready

#2156 release/14.5.5
  CHANGELOG.md
  package.json
Labels: ready, release

#2159 Remove postcss-loader from peer dependencies
  package.json
Labels: ready

#2136 [GUILD] Typescript `EmptyState`
  src/@types/@teamleader/ui-illustrations.d.ts
  src/components/emptyState/EmptyState.js
  src/components/emptyState/EmptyState.tsx
  src/components/emptyState/emptyState.stories.spec.tsx
  src/components/emptyState/emptyState.stories.tsx
  src/components/emptyState/index.ts
Labels: ready

#2134 [GUILD] TypeScript `EmailSelector`
  src/components/emailSelector/Autocomplete.tsx
  src/components/emailSelector/EmailSelector.tsx
  src/components/emailSelector/EmailSuggestion.tsx
  src/components/emailSelector/Label.tsx
  src/components/emailSelector/emailSelector.stories.spec.tsx
  src/components/emailSelector/emailSelector.stories.tsx
  src/components/emailSelector/index.ts
  src/components/emailSelector/types.ts
  src/components/emailSelector/utils.ts
Labels: ready, maintenance

#2127 [GUILD] Typescript Checkbox
  src/components/checkbox/Checkbox.tsx
  src/components/checkbox/checkbox.stories.tsx
  src/components/checkbox/index.ts
Labels: ready, maintenance

#2166 Typescript Section
  src/components/section/Section.js
  src/components/section/Section.tsx
  src/components/section/index.ts
  src/components/section/section.stories.tsx
Labels: ready

#2175 Dialog ref fix
  CHANGELOG.md
  src/components/dialog/Dialog.tsx
Labels: bug

#2177 Release/14.5.7
  CHANGELOG.md
  package.json
Labels: ready

#2181 Make dependabot ignore patch updates
  .github/dependabot.yml
Labels: dependencies, maintenance
