Repository teamleadercrm/ui, pull requests merged in 2022-07, with the labels that each got.

#2230 [GUILD] - Converting LabelValuePair to typescript
  src/components/labelValuePair/Label.js
  src/components/labelValuePair/Label.tsx
  src/components/labelValuePair/LabelValuePair.js
  src/components/labelValuePair/LabelValuePair.tsx
  src/components/labelValuePair/LabelValuePairGroup.js
  src/components/labelValuePair/LabelValuePairGroup.tsx
  src/components/labelValuePair/Value.js
  src/components/labelValuePair/Value.tsx
  src/components/labelValuePair/index.ts
  src/components/labelValuePair/labelPair.stories.tsx
Labels: ready

#2248 [GUILD] - Convert Pagination component to typescript
  src/components/pagination/Pagination.js
  src/components/pagination/Pagination.tsx
  src/components/pagination/index.ts
  src/components/pagination/pagination.stories.tsx
Labels: ready

#2252 [GUILD] Rewrite `PoweredByButton` in TS
  src/components/poweredByButton/PoweredByButton.tsx
  src/components/poweredByButton/index.ts
  src/components/poweredByButton/poweredByButton.stories.tsx
Labels: ready, maintenance

#2241 [GUILD] - Convert Menu to typescript
  src/components/menu/IconMenu.js
  src/components/menu/IconMenu.tsx
  src/components/menu/Menu.js
  src/components/menu/Menu.tsx
  src/components/menu/MenuDivider.tsx
  src/components/menu/MenuItem.js
  src/components/menu/MenuItem.tsx
  src/components/menu/MenuTitle.tsx
  src/components/menu/iconMenu.stories.tsx
  src/components/menu/index.ts
  src/components/menu/menu.stories.tsx
Labels: ready

#2251 [GUILD] Convert ahoy message component to typescript
  src/components/message/Message.js
  src/components/message/Message.tsx
  src/components/message/index.ts
  src/components/message/message.stories.tsx
Labels: maintenance

#2254 [GUILD] - Passport to Typescript
  src/components/avatar/Avatar.tsx
  src/components/badge/Badge.tsx
  src/components/link/Link.tsx
  src/components/passport/EmptyPassport.js
  src/components/passport/EmptyPassport.tsx
  src/components/passport/Passport.js
  src/components/passport/Passport.tsx
  src/components/passport/index.ts
  src/components/passport/passport.stories.tsx
Labels: maintenance

#2255 [GUILD] Rewrite `SplitButton` in TS
  src/components/buttonGroup/ButtonGroup.tsx
  src/components/splitButton/SplitButton.js
  src/components/splitButton/SplitButton.tsx
  src/components/splitButton/index.ts
  src/components/splitButton/splitButton.stories.tsx
  src/components/utils/isReactElement.ts
Labels: ready, maintenance

#2256 [Guild] Fix Storybook rendering of string | number union type
  src/components/input/input.stories.tsx
Labels: bug

#2264 Remove TSFixMe
  src/@types/global.d.ts
  src/components/datepicker/DatePickerInput.tsx
  src/components/input/Input.tsx
  src/components/popover/Popover.tsx
Labels: ready, types

#2263 Made handleShowScrollShadow optional
  CHANGELOG.md
  src/components/dialog/Body.tsx
Labels: ready

#2267 [FRAF-752] - Fix menu not working correctly
  src/components/menu/Menu.tsx
Labels: bug, ready

#2271 Input: only use state value when value is not passed as prop
  CHANGELOG.md
  src/components/input/Input.tsx
Labels: bug

#2273 Added exception for ckEditor elements in useFocusTrap
  CHANGELOG.md
  src/utils/useFocusTrap/useFocusTrap.tsx
Labels: bug, ready

#2280 LabelValuePair: decrease margin for the inline LabelValuePair
  CHANGELOG.md
  src/components/labelValuePair/LabelValuePair.tsx
  src/components/labelValuePair/labelPair.stories.tsx
Labels: enhancement

#2281 Fix bug on popover
  src/components/popover/positionCalculation.ts
Labels: bug

#2279 Added forwardRef to Icon
  CHANGELOG.md
  src/components/icon/Icon.tsx
Labels: ready

#2282 Release/15.0.4
  CHANGELOG.md
  package.json
Labels: release

#2283 Fix DatePicker InputProps
  src/components/datepicker/DatePickerInput.tsx
  src/components/popover/positionCalculation.ts
Labels: bug

#2284 Release/15.0.5
  CHANGELOG.md
  package.json
Labels: release

#2287 Add marketing dialog
  CHANGELOG.md
  src/components/marketingButton/MarketingButton.tsx
  src/components/marketingDialog/MarketingDialog.tsx
  src/components/marketingDialog/index.ts
  src/components/marketingDialog/marketingDialog.stories.tsx
  src/components/marketingDialog/theme.css
  src/index.ts
Labels: new component

#2297 Move @types/lodash.throttle to dev dependencies
  package.json
Labels: ready, dependencies
