Repository teamleadercrm/ui, pull requests merged in 2022-04, with the labels that each got.

#2072 release/14.0.0
  CHANGELOG.md
  package.json
Labels: ready, release

#2074 Allow passing rest props to DialogBase component
  CHANGELOG.md
  src/components/dialog/Dialog.js
  src/components/dialog/DialogBase.js
Labels: ready

#2081 Release/14.1.0
  CHANGELOG.md
  package.json
Labels: release

#2085 Add menu vertical offset
  CHANGELOG.md
  src/components/select/Select.js
  src/components/select/select.stories.js
Labels: ready

#2095 Fix types failing in stories files, only run `yarn build` on `prepublishOnly` instead of `prepare`
  package.json
  tsconfig.build.json
  tsconfig.json
Labels: ready

#2094 release/14.3.0
  CHANGELOG.md
  package.json
Labels: ready, release

#2097 release/14.3.1
  CHANGELOG.md
  package.json
Labels: ready, release

#2098 Fix build not including `Box` and `Counter` components
  CHANGELOG.md
  package.json
  src/components/box/index.ts
  src/index.ts
  tsconfig.build.json
Labels: bug, ready

#2099 release/14.3.2
  CHANGELOG.md
  package.json
Labels: release
