Repository teamleadercrm/ui, pull requests merged in 2022-03, with the labels that each got.

#2033 [FRAF-335] Add story with multiple Widget.Body
  src/components/widget/widget.stories.js
Labels: ready

#2040 `Dialog`: add draggable property
  CHANGELOG.md
  src/components/dialog/Dialog.js
  src/components/dialog/DialogBase.js
  src/components/dialog/theme.css
  src/components/dialog/useDraggable.js
Labels: enhancement

#2041 Add z-index to email selector overlay
  CHANGELOG.md
  src/components/emailSelector/Label.js
  src/components/emailSelector/theme.css
Labels: bug, ready

#2042 `Dialog`: prevent header title from wrapping to the next line, remove `headingLevel` property
  CHANGELOG.md
  src/components/dialog/Dialog.js
  src/components/dialog/Header.js
  src/components/dialog/theme.css
Labels: ready

#2045 🔖 bump version
  CHANGELOG.md
  package.json
Labels: release

#2058 [FRAF-414] Revise Dialog component
  CHANGELOG.md
  src/components/dialog/Dialog.js
  src/components/dialog/Footer.js
  src/components/dialog/Header.js
  src/components/dialog/dialog.stories.js
  src/components/dialog/dialog.stories.spec.js
Labels: ready, maintenance, feature, breaking

#2057 [FRAF-437] Alert component
  CHANGELOG.md
  index.d.ts
  package.json
  src/components/alert/Alert.js
  src/components/alert/alert.stories.js
  src/components/alert/alert.stories.spec.js
  src/components/alert/index.js
  src/components/button/Button.js
  src/components/button/index.js
  src/components/dialog/Dialog.js
  src/components/dialog/Footer.js
  src/index.js
  yarn.lock
Labels: ready, new component

#2062 release/12.5.0
  CHANGELOG.md
  package.json
Labels: ready, release

#2061 Consolidate label component
  .storybook/stories/playground/zIndexes.stories.js
  src/components/checkbox/Checkbox.js
  src/components/checkbox/theme.css
  src/components/label/Label.js
  src/components/label/label.stories.js
  src/components/radio/RadioButton.js
  src/components/radio/theme.css
  src/components/toggle/Toggle.js
  src/components/toggle/theme.css
Labels: ready, breaking

#2064 Release/13.0.0
  CHANGELOG.md
  package.json
Labels: release

#2066 Release/13.0.1
  CHANGELOG.md
  package.json
Labels: release
