Repository teamleadercrm/ui, pull requests merged in 2022-01, with the labels that each got.

#1888 removed `LoadingMolecule`
  CHANGELOG.md
  index.d.ts
  src/components/loadingMolecule/LoadingMolecule.js
  src/components/loadingMolecule/index.js
  src/components/loadingMolecule/loadingMolecule.stories.js
  src/components/loadingMolecule/theme.css
  src/index.js
Labels: ready, breaking

#1889 Removed StatusBullet, TimerPulser, DatePickerRange, DatePickerInputRange
  .storybook/stories/playground/zIndexes.stories.js
  CHANGELOG.md
  index.d.ts
  src/components/datepicker/DatePickerInputRange.js
  src/components/datepicker/DatePickerRange.js
  src/components/datepicker/datePicker.stories.js
  src/components/datepicker/index.js
  src/components/datepicker/theme.css
  src/components/statusBullet/StatusBullet.js
  src/components/statusBullet/index.js
  src/components/statusBullet/statusBullet.stories.js
  src/components/statusBullet/theme.css
  src/components/timerPulser/TimerPulser.js
  src/components/timerPulser/index.js
  src/components/timerPulser/theme.css
  src/components/timerPulser/timerPulser.stories.js
  src/index.js
Labels: ready, breaking

#1890 `Pagination, Button`: remove `inverse` property
  CHANGELOG.md
  src/components/button/Button.js
  src/components/button/button.stories.spec.js
  src/components/button/theme.css
  src/components/pagination/Pagination.js
  src/components/pagination/pagination.stories.js
  src/components/pagination/theme.css
Labels: ready, breaking

#1893 Fix security issues and dependency updates
  .eslintrc
  .storybook/main.js
  CHANGELOG.md
  package.json
  yarn.lock
Labels: ready, security

#1894 Clean up general Storybook structure and docs pages
  .env.development
  .env.production
  .eslintrc
  .storybook/preview.js
  .storybook/stories/about.stories.mdx
  .storybook/stories/about/about.stories.mdx
  .storybook/stories/changelog.stories.mdx
  .storybook/stories/colors.stories.mdx
  .storybook/stories/colors/colors.stories.mdx
  .storybook/stories/depths/assets/depths.svg
  .storybook/stories/depths/depths.stories.mdx
  .storybook/stories/icons/assets/bounding_1.svg
  .storybook/stories/icons/assets/bounding_2.svg
  .storybook/stories/icons/assets/bounding_3.svg
  .storybook/stories/icons/assets/bounding_4.svg
  .storybook/stories/icons/assets/placement.svg
  .storybook/stories/icons/assets/secondary_metaphors.svg
  .storybook/stories/icons/icons.stories.mdx
  .storybook/utils/index.js
  .storybook/webpack.config.js
  CHANGELOG.md
  src/components/icon/description.md
  src/components/icon/icon.stories.js
  src/components/illustration/description.md
  src/components/illustration/illustration.stories.js
  src/components/typography/typography.stories.js
Labels: ready, storybook

#1900 Fix storybook deprecation and UI library react warning
  .storybook/manager.js
  .storybook/stories/colors.stories.mdx
  .storybook/stories/playground/forms.stories.js
  .storybook/stories/playground/zIndexes.stories.js
  src/components/badge/badge.stories.js
  src/components/button/button.stories.js
  src/components/buttonGroup/buttonGroup.stories.js
  src/components/checkbox/checkbox.stories.js
  src/components/counter/counter.stories.js
  src/components/datepicker/datePicker.stories.js
  src/components/detailPage/detailPage.stories.js
  src/components/iconButton/iconButton.stories.js
  src/components/illustration/illustration.stories.js
  src/components/input/input.stories.js
  src/components/overviewPage/overviewPage.stories.js
  src/components/popover/popover.stories.js
  src/components/tab/tab.stories.js
  src/components/toast/toast.stories.js
  src/components/tooltip/tooltip.stories.js
  src/components/typography/typography.stories.js
Labels: storybook

#1914 Use group constants instead of a hardcoded value in .mdx files
  .storybook/stories/colors.stories.mdx
Labels: ready

#1931 Fix processing state of tiny buttons in UI-library
  CHANGELOG.md
  src/components/button/Button.js
Labels: bug, ready

#1925 Create separate badged link component instead of link with icon and badged property
  CHANGELOG.md
  index.d.ts
  src/components/badgedLink/BadgedLink.js
  src/components/badgedLink/badgedLink.stories.js
  src/components/badgedLink/badgedLink.stories.spec.js
  src/components/badgedLink/index.js
  src/components/badgedLink/theme.css
  src/components/detailPage/DetailPageHeader.js
  src/components/detailPage/theme.css
  src/components/link/Link.js
  src/components/link/link.stories.js
  src/components/link/theme.css
  src/index.js
Labels: ready, new component, breaking

#1937 Release/12.0.0
  CHANGELOG.md
  package.json
Labels: release

#1940 IconButton: add processing state
  CHANGELOG.md
  src/components/iconButton/IconButton.js
  src/components/iconButton/iconButton.stories.js
  src/components/iconButton/theme.css
Labels: ready, feature

#1938 Restored mouse event propagation in `Overlay` component
  CHANGELOG.md
  src/components/overlay/Overlay.js
Labels: bug, ready

#1944 Release/12.1.0
  CHANGELOG.md
  package.json
Labels: ready, release
