Repository teamleadercrm/ui, pull requests merged in 2022-11, with the labels that each got.

#2431 Revert back tabIndex on Overlay
  src/components/overlay/Overlay.tsx
Labels: bug

#2438 Updated readme with new release process
  README.md
Labels: ready

#2432 Release/16.4.4
  CHANGELOG.md
  package.json
Labels: release

#2430 Making DatePickerInput typeable (again)
  CHANGELOG.md
  src/components/datepicker/DatePicker.tsx
  src/components/datepicker/DatePickerInput.tsx
  src/components/datepicker/datePicker.stories.tsx
  src/components/datepicker/datePickerInput.stories.tsx
  src/components/datepicker/localeUtils.ts
  src/components/datepicker/theme.css
  src/components/input/Input.tsx
  src/components/popover/Popover.tsx
Labels: enhancement, ready

#2439 Release/16.5.0
  CHANGELOG.md
  package.json
Labels: ready, release

#2441 Fix DatePickerInput inability to click on MonthPicker in Dialog
  CHANGELOG.md
  package.json
  src/components/datepicker/DatePickerInput.tsx
  src/components/datepicker/__tests__/utils.spec.ts
  src/components/datepicker/datePickerInput.stories.tsx
  src/components/datepicker/utils.ts
  src/components/select/Select.tsx
  src/utils/useFocusTrap/useFocusTrap.tsx
Labels: bug, ready

#2440 Tweak select menu margins
  CHANGELOG.md
  src/components/select/Select.tsx
  src/components/select/select.stories.tsx
  src/static/data/select.ts
Labels: enhancement, ready

#2445 Bring back button blur
  CHANGELOG.md
  package.json
  src/components/button/Button.tsx
Labels: ready

#2447 Call `onChange` prop in input blur of DatePickerInput
  CHANGELOG.md
  package.json
  src/components/datepicker/DatePickerInput.tsx
Labels: bug, ready

#2451 Make sure to stop the NumericInput `mouseDown` loops when max value or min value is reached
  .storybook/stories/playground/numericInput.stories.tsx
  CHANGELOG.md
  src/components/input/NumericInput.tsx
Labels: bug, ready

#2448 Properly call `onChange` in DatePickerInput
  CHANGELOG.md
  package.json
  src/components/datepicker/DatePicker.tsx
  src/components/datepicker/DatePickerInput.tsx
  src/components/datepicker/datePickerInput.stories.tsx
  src/components/datepicker/localeUtils.ts
  src/components/select/Select.tsx
  src/utils/useFocusTrap/useFocusTrap.tsx
Labels: bug, ready, release

#2461 Version correction
  package.json
Labels: release

#2465 Make `MessageProps` extend `BoxProps`
  CHANGELOG.md
  src/components/message/Message.tsx
  src/components/message/message.stories.tsx
Labels: enhancement, ready

#2464 DatePickerInput: fixed clearing logic
  CHANGELOG.md
  package.json
  src/components/datepicker/DatePickerInput.tsx
Labels: ready

#2467 Use typed SelectProps
  CHANGELOG.md
  package.json
  src/components/marketingMenuItem/marketingMenuItem.stories.tsx
  src/components/select/Select.tsx
  src/components/select/types.ts
Labels: ready, release
