Repository teamleadercrm/ui, pull requests merged in 2022-09, with the labels that each got.

#2344 [FRAF-909] - Fix bug (first item getting focused on menu item)
  CHANGELOG.md
  src/components/menu/Menu.tsx
  src/components/menu/theme.css
Labels: bug, hold

#2345 Release/16.0.3
  CHANGELOG.md
  package.json
Labels: release

#2351 Fix close button alignment issue
  CHANGELOG.md
  src/components/dialog/theme.css
Labels: bug

#2352 Release/16.0.4
  CHANGELOG.md
  package.json
Labels: release

#2356 Guild/typescript tooltip
  src/components/avatar/Avatar.tsx
  src/components/avatar/AvatarStackOverflow.tsx
  src/components/badge/Badge.tsx
  src/components/filterSelection/FilterSelection.tsx
  src/components/hoc/DocumentObjectProvider/DocumentObjectProvider.tsx
  src/components/tooltip/Tooltip.js
  src/components/tooltip/Tooltip.tsx
  src/components/tooltip/index.js
  src/components/tooltip/index.tsx
  src/components/tooltip/tooltip.stories.tsx
  src/index.ts
Labels: ready, maintenance

#2355 Toggle with tooltip
  CHANGELOG.md
  src/components/toggle/Toggle.tsx
  src/components/toggle/theme.css
  src/components/toggle/toggle.stories.tsx
Labels: enhancement, hold

#2364 Made children prop of Tooltip optional
  CHANGELOG.md
  src/components/tooltip/Tooltip.tsx
Labels: enhancement, ready

#2365 Release/16.1.1
  CHANGELOG.md
  package.json
Labels: ready, release

#2369 Allow more control over SplitButton component
  CHANGELOG.md
  src/components/splitButton/SplitButton.tsx
  src/components/splitButton/splitButton.stories.tsx
Labels: ready

#2372 Release/16.2.0
  CHANGELOG.md
  package.json
Labels: release

#2374 Fix tooltip tooltipActive prop
  CHANGELOG.md
  src/components/tooltip/Tooltip.tsx
  src/components/tooltip/tooltip.stories.tsx
Labels: bug, ready

#2375 Release/16.2.1
  CHANGELOG.md
  package.json
Labels: release

#2376 DatePickerInput fixes
  CHANGELOG.md
  src/components/datepicker/DatePickerInput.tsx
Labels: bug, ready

#2379 Release/16.2.2
  CHANGELOG.md
  package.json
Labels: release

#2384 [FRONT-116] Datepicker: use fixed amount of weeks
  CHANGELOG.md
  src/components/datepicker/DatePicker.tsx
  src/components/datepicker/datePicker.stories.tsx
Labels: enhancement, ready

#2387 Add `clearable` prop to DatePickerInput
  CHANGELOG.md
  src/components/datepicker/DatePickerInput.tsx
  src/components/datepicker/datePicker.stories.tsx
Labels: enhancement, ready

#2388 Fix toast label action
  CHANGELOG.md
  src/components/toast/Toast.tsx
  src/components/toast/theme.css
Labels: bug, ready

#2380 Numeric input stepper customisation
  .storybook/stories/playground/numericInput.stories.tsx
  CHANGELOG.md
  src/components/input/NumericInput.tsx
Labels: enhancement, feature

#2389 Release/16.3.0
  CHANGELOG.md
  package.json
Labels: ready, release

#2390 Make date picker input cursor default
  CHANGELOG.md
  src/components/datepicker/DatePickerInput.tsx
  src/components/datepicker/theme.css
  src/components/toast/theme.css
Labels: ready

#2391 Set menu width on month picker
  CHANGELOG.md
  src/components/datepicker/MonthPicker.tsx
Labels: enhancement, ready

#2392 Added smaller bottom margin for small sized label
  CHANGELOG.md
  src/components/label/Label.tsx
  src/components/label/theme.css
Labels: enhancement, ready

#2393 Release/16.4.0
  CHANGELOG.md
  package.json
Labels: ready, release

#2394 Fix escape key closing on overlays
  CHANGELOG.md
  src/components/overlay/Overlay.tsx
Labels: bug, ready
