Repository teamleadercrm/ui, pull requests merged in 2022-12, with the labels that each got.

#2474 [FIX] Looping of menu item
  CHANGELOG.md
  package.json
  src/components/menu/Menu.tsx
Labels: bug

#2481 ⬇️ Revert back Menu
  CHANGELOG.md
  package.json
  src/components/menu/Menu.tsx
Labels: bug

#2490 Add missing `data-teamleader-ui` attribute to some components
  CHANGELOG.md
  src/components/advancedCollapsible/AdvancedCollapsible.tsx
  src/components/avatar/AvatarOverlay.tsx
  src/components/container/Container.tsx
  src/components/datepicker/DatePickerInput.tsx
  src/components/detailPage/DetailPage.tsx
  src/components/detailPage/DetailPageBody.tsx
  src/components/detailPage/DetailPageHeader.tsx
  src/components/emailSelector/EmailSelector.tsx
  src/components/emptyState/EmptyState.tsx
  src/components/filterSelection/FilterSelection.tsx
  src/components/input/DurationInput.tsx
  src/components/input/NumericInput.tsx
  src/components/input/Textarea.tsx
  src/components/input/TimeInput.tsx
  src/components/island/IslandGroup.tsx
  src/components/label/Label.tsx
  src/components/labelValuePair/LabelValuePair.tsx
  src/components/labelValuePair/LabelValuePairGroup.tsx
  src/components/marketingLockBadge/MarketingLockBadge.tsx
  src/components/marketingMarker/MarketingMarker.tsx
  src/components/marketingStatusLabel/MarketingStatusLabel.tsx
  src/components/marketingTypography/MarketingHeading1.tsx
  src/components/marketingTypography/MarketingHeading2.tsx
  src/components/message/Message.tsx
  src/components/overviewPage/OverviewPage.tsx
  src/components/overviewPage/OverviewPageBody.tsx
  src/components/overviewPage/OverviewPageHeader.tsx
  src/components/passport/EmptyPassport.tsx
  src/components/passport/Passport.tsx
  src/components/poweredByButton/PoweredByButton.tsx
  src/components/progressTracker/ProgressTracker.tsx
  src/components/select/Select.tsx
  src/components/typography/Marker.tsx
  src/components/widget/Widget.tsx
  src/components/wysiwygEditor/WysiwygEditor.tsx
Labels: maintenance

#2492 [FIX] Break long words in order to prevent text overflow
  CHANGELOG.md
  package.json
  src/components/toast/theme.css
Labels: bug, ready

#2494 FIX: Add release date to CHANGELOG.md
  CHANGELOG.md
Labels: ready, maintenance

#2498 [Date picker] Allow configuring initial month
  CHANGELOG.md
  src/components/datepicker/DatePicker.tsx
  src/components/datepicker/datePicker.stories.tsx
Labels: enhancement
