Repository teamleadercrm/ui, pull requests merged in 2022-10, with the labels that each got.

#2396 [GUILD] Typescript Island
  src/components/island/Island.tsx
  src/components/island/IslandGroup.tsx
  src/components/island/index.js
  src/components/island/index.ts
  src/components/island/island.stories.tsx
  src/components/island/islandGroup.stories.tsx
  src/index.ts
Labels: enhancement, types

#2116 [GUILD] Typescript banner
  src/components/banner/Banner.js
  src/components/banner/Banner.tsx
  src/components/banner/banner.stories.spec.tsx
  src/components/banner/banner.stories.tsx
  src/components/banner/index.js
  src/components/banner/index.ts
  src/components/section/Section.tsx
  src/components/section/index.ts
  src/index.ts
Labels: ready, maintenance, types

#2399 [GUILD] Set more specific `onClose` type on `Banner`
  src/components/banner/Banner.tsx
Labels: types

#2401 Guild/typescript miscellaneous
  .babelrc
  .storybook/main.ts
  .storybook/manager.ts
  .storybook/preview.ts
  .storybook/stories/playground/dialogs.stories.tsx
  .storybook/stories/playground/forms.stories.tsx
  .storybook/stories/playground/zIndexes.stories.tsx
  .storybook/theme.ts
  .storybook/utils/index.ts
  README.md
  package.json
  src/components/advancedCollapsible/AdvancedCollapsible.tsx
  src/components/advancedCollapsible/advancedCollapsable.stories.spec.tsx
  src/components/badge/Badge.tsx
  src/components/badge/badge.stories.spec.tsx
  src/components/box/boxProps.ts
  src/components/button/Button.tsx
  src/components/button/button.stories.spec.tsx
  src/components/checkbox/Checkbox.tsx
  src/components/checkbox/checkbox.stories.spec.tsx
  src/components/input/utils.js
  src/components/input/utils.ts
  src/components/island/Island.tsx
  src/components/menu/Menu.tsx
  src/components/select/Select.tsx
  src/components/utils/events.js
  src/components/utils/events.ts
  src/components/utils/index.ts
  src/components/utils/utils.js
  src/components/utils/utils.ts
  src/constants/index.ts
  src/constants/keys.ts
  src/static/data/avatar.ts
  src/static/data/datagrid.ts
  src/static/data/languages.ts
  src/static/data/tab.ts
  yarn.lock
Labels: ready

#2408 Label margin bottom set by default and not by size
  CHANGELOG.md
  src/components/label/Label.tsx
  src/components/label/theme.css
Labels: ready

#2412 Fix dialog being to big on Safari
  src/components/dialog/theme.css
  src/components/overlay/theme.css
Labels: bug

#2414 Release/16.4.1
  CHANGELOG.md
  package.json
Labels: release

#2418 Adjustment of Wysiwyg props and export of SelectRef
  CHANGELOG.md
  src/components/select/Select.tsx
  src/components/select/index.tsx
  src/components/wysiwygEditor/WysiwygEditor.tsx
  src/index.ts
Labels: enhancement, ready

#2419 Release/16.4.2
  CHANGELOG.md
  package.json
Labels: release

#2422 🐛 Fix the blocking of selects when multiple are rendered
  CHANGELOG.md
  src/components/select/Select.tsx
Labels: bug

#2423 [16.4.3] - 22-10-31
  CHANGELOG.md
  package.json
Labels: release
