Repository teamleadercrm/ui, pull requests merged in 2022-06, with the labels that each got.

#2185 [FRAF-544] Flex component
  CHANGELOG.md
  src/components/flex/Flex.tsx
  src/components/flex/flex.stories.tsx
  src/components/flex/index.ts
  src/components/flex/theme.css
  src/index.ts
Labels: new component

#2186 [FRAF-545] Grid component
  CHANGELOG.md
  src/components/grid/Grid.tsx
  src/components/grid/GridItem.tsx
  src/components/grid/grid.stories.tsx
  src/components/grid/index.ts
  src/components/grid/theme.css
  src/index.ts
Labels: new component

#2187 Release/14.6.0
  CHANGELOG.md
  package.json
Labels: release

#2188 Allow any react node in the dialog title
  src/components/dialog/Dialog.tsx
Labels: ready

#2191 Fix Dialog content blurriness in webkit
  CHANGELOG.md
  src/components/dialog/theme.css
  src/components/dialog/useDraggable.ts
Labels: bug, ready

#2198 release/14.6.1
  CHANGELOG.md
  package.json
Labels: ready, release

#2197 Add ability to remove the remove button from the first item in EmailSelector
  CHANGELOG.md
  src/components/emailSelector/EmailSelector.tsx
  src/components/emailSelector/Label.tsx
  src/components/emailSelector/emailSelector.stories.tsx
Labels: feature

#2207 Allow tooltip props in label
  .storybook/main.js
  CHANGELOG.md
  package.json
  src/components/label/Label.tsx
  yarn.lock
Labels: ready

#2205 [TIDAL-2039] Email selector menu can be the same width as input
  CHANGELOG.md
  src/components/emailSelector/Autocomplete.tsx
  src/components/emailSelector/EmailSelector.tsx
  src/components/emailSelector/Label.tsx
  src/components/emailSelector/emailSelector.stories.tsx
  src/components/emailSelector/theme.css
Labels: ready

#2211 Release/14.7.1
  CHANGELOG.md
  package.json
Labels: release

#2212 Improved component types
  src/components/alert/Alert.tsx
  src/components/label/Label.tsx
Labels: ready

#2213 Release/14.7.1 release
  CHANGELOG.md
  package.json
Labels: release

#2214 Grid: columnGap and rowGap props
  CHANGELOG.md
  src/components/grid/Grid.tsx
  src/components/grid/grid.stories.tsx
  src/components/grid/theme.css
Labels: ready

#2219 Release/14.8.0
  CHANGELOG.md
  package.json
Labels: release

#2231 Generic component type
  src/@types/types.ts
  src/components/advancedCollapsible/AdvancedCollapsible.tsx
  src/components/alert/Alert.tsx
  src/components/avatar/Avatar.tsx
  src/components/avatar/AvatarAdd.tsx
  src/components/avatar/AvatarAnonymous.tsx
  src/components/avatar/AvatarImage.tsx
  src/components/avatar/AvatarInitials.tsx
  src/components/avatar/AvatarOverlay.tsx
  src/components/avatar/AvatarStack.tsx
  src/components/avatar/AvatarStackOverflow.tsx
  src/components/avatar/AvatarTeam.tsx
  src/components/badge/Badge.tsx
  src/components/badgedLink/BadgedLink.tsx
  src/components/box/Box.tsx
  src/components/button/Button.tsx
  src/components/checkbox/Checkbox.tsx
  src/components/container/Container.tsx
  src/components/counter/Counter.tsx
  src/components/detailPage/DetailPage.tsx
  src/components/detailPage/DetailPageBody.tsx
  src/components/detailPage/DetailPageHeader.tsx
  src/components/dialog/Body.tsx
  src/components/dialog/Dialog.tsx
  src/components/dialog/DialogBase.tsx
  src/components/dialog/Footer.tsx
  src/components/dialog/Header.tsx
  src/components/dialog/useDraggable.ts
  src/components/emailSelector/Autocomplete.tsx
  src/components/emailSelector/EmailSelector.tsx
  src/components/emailSelector/EmailSuggestion.tsx
  src/components/emailSelector/Label.tsx
  src/components/emptyState/EmptyState.tsx
  src/components/filterSelection/FilterSelection.tsx
  src/components/flex/Flex.tsx
  src/components/grid/Grid.tsx
  src/components/grid/GridItem.tsx
  src/components/icon/Icon.tsx
  src/components/icon/icon.stories.tsx
  src/components/iconButton/IconButton.tsx
  src/components/iconButton/iconButton.stories.spec.tsx
  src/components/illustration/illustration.stories.tsx
  src/components/label/Label.tsx
  src/components/link/Link.tsx
  src/components/loadingBar/LoadingBar.tsx
  src/components/loadingSpinner/LoadingSpinner.tsx
  src/components/marketingButton/MarketingButton.tsx
  src/components/section/Section.tsx
  src/components/tab/TabGroup.tsx
  src/components/tab/TitleTab.tsx
  src/components/toggle/Toggle.tsx
  src/utils/useFocusTrap/useFocusTrap.tsx
Labels: ready, maintenance

#2236 [GUILD] Typescript `MarketingLockBadge`
  src/components/marketingLink/MarketingLink.tsx
  src/components/marketingLockBadge/MarketingLockBadge.js
  src/components/marketingLockBadge/MarketingLockBadge.tsx
  src/components/marketingLockBadge/index.ts
  src/components/marketingLockBadge/marketingLockBadge.stories.tsx
Labels: ready, maintenance

#2226 [GUILD] Typescript StatusLabel
  src/components/statusLabel/StatusLabel.js
  src/components/statusLabel/StatusLabel.tsx
  src/components/statusLabel/index.tsx
  src/components/statusLabel/statusLabel.stories.tsx
Labels: ready, maintenance

#2233 [GUILD] Typescript `hoc`
  src/components/hoc/DocumentObjectProvider/DocumentObjectProvider.tsx
  src/components/hoc/DocumentObjectProvider/index.ts
Labels: ready, maintenance

#2242 [GUILD] - Convert OverviewPage component
  src/components/overviewPage/OverviewPage.js
  src/components/overviewPage/OverviewPage.tsx
  src/components/overviewPage/OverviewPageBody.js
  src/components/overviewPage/OverviewPageBody.tsx
  src/components/overviewPage/OverviewPageHeader.js
  src/components/overviewPage/OverviewPageHeader.tsx
  src/components/overviewPage/index.ts
  src/components/overviewPage/overviewPage.stories.tsx
Labels: ready

#2249 [GUILD] Typescript `Toast`
  src/components/toast/Toast.js
  src/components/toast/Toast.tsx
  src/components/toast/ToastContainer.js
  src/components/toast/ToastContainer.tsx
  src/components/toast/index.tsx
  src/components/toast/toast.stories.tsx
Labels: ready, maintenance

#2246 [GUILD] Typescript Timer
  CHANGELOG.md
  src/components/timer/Timer.tsx
  src/components/timer/index.tsx
  src/components/timer/timer.stories.tsx
Labels: ready, maintenance

#2238 [GUILD] Typescript `MarketingStatusLabel`
  src/components/marketingStatusLabel/MarketingStatusLabel.js
  src/components/marketingStatusLabel/MarketingStatusLabel.tsx
  src/components/marketingStatusLabel/index.ts
  src/components/marketingStatusLabel/marketingStatusLabel.stories.tsx
Labels: ready, maintenance

#2237 [GUILD] Typescript `MarketingMarker`
  src/components/marketingMarker/MarketingMarker.js
  src/components/marketingMarker/MarketingMarker.tsx
  src/components/marketingMarker/index.ts
  src/components/marketingMarker/marketingMarker.stories.tsx
Labels: ready, maintenance

#2232 [GUILD] Typescript `MarketingButtonGroup`
  src/components/marketingButtonGroup/Button.js
  src/components/marketingButtonGroup/Button.tsx
  src/components/marketingButtonGroup/MarketingButtonGroup.js
  src/components/marketingButtonGroup/MarketingButtonGroup.tsx
  src/components/marketingButtonGroup/index.ts
  src/components/marketingButtonGroup/marketingButtonGroup.stories.tsx
Labels: ready, maintenance
