Repository teamleadercrm/ui, pull requests merged in 2023-01, with the labels that each got.

#2511 `AdvancedCollapsible` - add `defaultIsCollapsed` prop
  CHANGELOG.md
  package.json
  src/components/advancedCollapsible/AdvancedCollapsible.tsx
Labels: enhancement

#2515 AdvancedCollapsible: children indent
  CHANGELOG.md
  src/components/advancedCollapsible/AdvancedCollapsible.tsx
  src/components/advancedCollapsible/theme.css
Labels: ready, feature

#2517 Bump @teamleader/ui-colors from 0.3.0 to 1.1.0
  package.json
  src/components/icon/__tests__/icon.stories.spec.tsx
  src/components/iconButton/__tests__/iconButton.stories.spec.tsx
  src/constants/colors.ts
  src/constants/index.ts
  yarn.lock
Labels: dependencies, hold

#2519 `WysiwygEditor` - Change link icon color
  CHANGELOG.md
  package.json
  src/components/wysiwygEditor/decorators/linkDecorator.tsx
Labels: enhancement

#2523 📝 Update changelog
  CHANGELOG.md
Labels: ready

#2524 🔖 Version bump
  package.json
Labels: ready

#2521 Fix menu onSelect type
  CHANGELOG.md
  src/components/menu/Menu.tsx
  src/components/menu/menu.stories.tsx
Labels: enhancement, types

#2544 `MarketingStatusLabel` - make `Icon` optional and configurable
  CHANGELOG.md
  package.json
  src/components/marketingStatusLabel/MarketingStatusLabel.tsx
  src/components/marketingStatusLabel/__tests__/MarketingStatusLabel.spec.tsx
  src/components/marketingStatusLabel/__tests__/__snapshots__/MarketingStatusLabel.spec.tsx.snap
  src/components/marketingStatusLabel/marketingStatusLabel.stories.tsx
Labels: ready, breaking

#2545 [MarketingStatusLabel] Hide margin when no Icon is provided
  CHANGELOG.md
  package.json
  src/components/marketingStatusLabel/MarketingStatusLabel.tsx
  src/components/marketingStatusLabel/__tests__/__snapshots__/MarketingStatusLabel.spec.tsx.snap
Labels: bug, ready
