Repository teamleadercrm/ui, pull requests merged in 2023-02, with the labels that each got.

#2548 [FEATURE] Support "tiny" size for Label
  CHANGELOG.md
  package.json
  src/components/label/Label.tsx
Labels: ready, feature

#2560 [Removed] Tiny label size
  CHANGELOG.md
  package.json
  src/components/label/Label.tsx
Labels: ready

#2576 [FRONT-441] fix the focus state for the Link and MarketingLink component
  CHANGELOG.md
  src/components/link/theme.css
  src/components/marketingLink/theme.css
Labels: bug

#2582 [FRONT-443] Avoid DataGrid error when hovering
  CHANGELOG.md
  src/components/datagrid/DataGrid.tsx
Labels: bug
