Repository teamleadercrm/ui, pull requests merged in 2023-05, with the labels that each got.

#2642 Make cursor a pointer on select inputs
  CHANGELOG.md
  package.json
  src/components/filterSelection/FilterSelection.tsx
  src/components/filterSelection/theme.css
  src/components/select/Select.tsx
  src/components/select/__tests__/__snapshots__/Select.spec.tsx.snap
Labels: enhancement

#2648 Spread all other props & add title prop
  CHANGELOG.md
  src/components/menu/IconMenu.tsx
Labels: feature

#2649 `Select` - Fix clear indicator styles
  CHANGELOG.md
  package.json
  src/components/select/Select.tsx
  src/components/select/__tests__/__snapshots__/Select.spec.tsx.snap
  src/components/select/theme.css
Labels: enhancement

#2652 Define default state value
  CHANGELOG.md
  src/components/input/Input.tsx
Labels: bug

#2660 [FRONT-370] support all Box props on the Flex component
  CHANGELOG.md
  src/components/flex/Flex.tsx
  src/components/flex/__tests__/__snapshots__/Flex.spec.tsx.snap
  src/components/flex/theme.css
  src/components/marketingDialog/__tests__/__snapshots__/MarketingDialog.spec.tsx.snap
Labels: maintenance, feature
